/*********************************/

/*MOSTLY NEEDED TOOL MOD [MNT] v.2.0*/

/*********************************/
/**********************************

Copyright © 2016 MCPEMoverz

Do Not Redistribute Or Remodify Without Permission!

**********************************/
/*********************************/


var modPath = android.os.Environment.getExternalStorageDirectory().getAbsolutePath() +"/games/com.mojang/minecraftpe/MNT/";
var font = " AAEAAAANAIAAAwBQRkZUTV/JAIgAAEcgAAAAHEdERUYBAwAkAABG+AAAAChPUy8yZsMzdwAAAVgAAABgY21hcG6etckAAAUIAAABomdhc3D//wADAABG8AAAAAhnbHlmwglSaQAACFgAADdYaGVhZPk9cqMAAADcAAAANmhoZWEIgwHUAAABFAAAACRobXR4OJ0AAAAAAbgAAANObG9jYaVll4IAAAasAAABqm1heHAA3wAqAAABOAAAACBuYW1lJ/FDLgAAP7AAAAUTcG9zdNmblGkAAETEAAACKwABAAAAAQAA+92lvl8PPPUACwQAAAAAAMtPFtMAAAAAy08W0/+A/wAEAAUAAAAACAACAAAAAAAAAAEAAAUA/wAAAASA/4D9gAQAAAEAAAAAAAAAAAAAAAAAAADTAAEAAADUACgACgAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAgKpAZAABQAEAgACAAAA/8ACAAIAAAACAAAzAMwAAAAABAAAAAAAAACgAAAHQAAACgAAAAAAAAAARlNUUgBAACD7AgOA/4AAAAUAAQAAAAH7AAAAAAKAA4AAAAAgAAEBAAAAAAAAAAKOAAACjgAAAQAAAAKAAAADAAAAAwAAAAMAAAADAAAAAYAAAAKAAAACgAAAAoAAAAMAAAABAAAAAwAAAAEAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAEAAAABAAAAAoAAAAMAAAACgAAAAwAAAAOAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAIAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAIAAAADAAAAAgAAAAMAAAADAAAAAYAAAAMAAAADAAAAAwAAAAMAAAADAAAAAoAAAAMAAAADAAAAAQAAAAMAAAACgAAAAYAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAACAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAoAAAAEAAAACgAAAA4AAAAEAAAADAAAAAwAAAAKAAAADAAAAAQAAAAKAAAADAAAAA4AAAAIAAAADAAAAAwAAAAMAAAADgAAAAwAAAAIAAAADgAAAAoAAAAKAAAABgAAABAAAAASAAAABgAAAAgAAAAGAAAACAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAABgAAAAgAAgAIAAAACAAAAAwD/gAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAACgAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAGAAAABgAAAAQAAAAIAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAA4AAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAIAAAADAAAAAwAAAAMAAAADAAAAAYAAAAGAAAABgAAAAYAAAAKAAAACgAAAAoAAAAMAAAACAAAAAwAAAAIAAAACAAAAAwAAAAOAAAADAAAAAAAAAAAAAAMAAAADAAAAHAABAAAAAACcAAMAAQAAABwABACAAAAAHAAQAAMADAB+AP8BeB6eIBQgHiAgICIgJiA6IKwhIvsC//8AAAAgAKEBeB6eIBQgGCAgICIgJiA5IKwhIvsB////4//B/0niJOCv4Kzgq+Cq4KfgleAk368F0QABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQYAAAEAAAAAAAAAAQIAAAACAAAAAAAAAAAAAAAAAAAAAQAAAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGEAhYaIipKXnaKho6Wkpqiqqausrq2vsLK0s7W3tru6vL3LcWNkaMx3oG9q0XVpAIeZAHIAAGZ2AAAAAABrewCnuYBibQAAAABsfM0AgYSWAAAAw8jJxMW4AMDBANDOz9LTAHjGygCDi4KMiY6PkI2UlQCTm5yaAAAAcAAAAHkAAAAAAAAAAAwADAAMAAwAHgA8AGwAmgDMAQwBHgFCAWYBigGiAa4BugHGAegCGAIuAmAClAK4At4DBgMkA1oDhgOaA64D3APwBBwESARuBIwEsgTWBPAFBgUaBTwFVAVoBYAFrgW8BeAGBAYkBkAGbAaOBroGzAbmBw4HMgdsB5AHuAfKB/IIBAgmCDIIRghmCIoIrgjQCPAJDAkwCVAJYgmCCawJvgniCfgKGAo+CmIKggqkCsAK1gr6CxQLTAtsC4wLsgvGC+wMCgwcDE4MdgysDOAM9A0oDToNZA14DbYNxg3SDfoOBg4kDkIOXg54DooOpg7IDtQO7g7+DxwPWA+MD8YP/BAkEE4QdhCkEMgQ8hEaETwRchGWEbgR4BIEEhwSNBJSEmoSjhK4EuYTEhNCE2oTmBPQFAAUJhRMFGwUkhTCFOIVCBUwFVYVfBWiFc4WABYsFmIWihawFtYXAhcWFygXQBdeF4YXohfKF/IYHhhGGHQYkBi4GNQY8BkMGSwZWBl2GaIZ0hn0GgAaEhokGjYaShpoGoYapBq8GtAa6BsKGywbUBtqG44brAAAAAEAAAAAA4ADgAADAAAxESERA4ADgPyAAAIAAAAAAIADgAADAAcAADE1MxUDETMRgICAgIABAAKA/YAAAAQAAAIAAgADgAADAAcACwAPAAARNTMVMzUzFSURMxEzETMRgICA/wCAgIACAICAgICAAQD/AAEA/wAAAAIAAAAAAoADgAADAB8AAAE1IxUDESM1MzUjNTMRMxEzETMRMxUjFTMVIxEjESMRAYCAgICAgICAgICAgICAgIABgICA/oABAICAgAEA/wABAP8AgICA/wABAP8AAAAAAAUAAAAAAoADgAAHAAsADwATABsAACE1ITUhFSMVEzUzFSU1IRUlNTMVPQEzNTMVIRUBAP8AAgCAgID+AAGA/gCAgIABAICAgIABAICAgICAgICAgICAgIAAAAAABwAAAAACgAOAAAMABwALAA8AEwAXABsAADE1MxUhETMRJREzGQE1MxU1ETMRJREzESU1MxWAAYCA/gCAgID+AIABgICAgAEA/wCAAQD/AAEAgICAAQD/AIABAP8AgICAAAAAAAgAAAAAAoADgAADAAcACwAPABsAHwAjACcAADM1IRUzNTMVJREzEQE1MxUBNSM1IzUzNTMRMxEBNTMVMzUzFSU1MxWAAQCAgP2AgAGAgP8AgICAgID+gICAgP8AgICAgICAAQD/AAEAgID/AICAgID/AP8AAgCAgICAgICAAAAAAgAAAgABAAOAAAMABwAAETUzFTURMxGAgAIAgICAAQD/AAAABQAAAAACAAOAAAMABwALAA8AEwAAITUhFSU1MxUlETMZATUzFT0BIRUBAAEA/oCA/wCAgAEAgICAgICAAYD+gAGAgICAgIAABQAAAAACAAOAAAMABwALAA8AEwAAMTUhFT0BMxU1ETMRATUzFSU1IRUBAICA/wCA/oABAICAgICAgAGA/oABgICAgICAAAAABQAAAQACAAKAAAMABwALAA8AEwAAETUzFSE1MxUlNSEVJTUzFSE1MxWAAQCA/oABAP6AgAEAgAEAgICAgICAgICAgICAAAAAAQAAAIACgAMAAAsAACURITUhETMRIRUhEQEA/wABAIABAP8AgAEAgAEA/wCA/wAAAQAA/4AAgAEAAAMAABURMxGAgAGA/oAAAQAAAYACgAIAAAMAABE1IRUCgAGAgIAAAQAAAAAAgAEAAAMAADERMxGAAQD/AAAABQAAAAACgAOAAAMABwALAA8AEwAAMTUzFTURMxkBNTMVNREzGQE1MxWAgICAgICAgAEA/wABAICAgAEA/wABAICAAAAFAAAAAAKAA4AAAwAHAA8AFwAbAAAzNSEVATUzFQERMxEzFSMVIREjNTM1MxEBNSEVgAGA/wCA/oCAgIABgICAgP4AAYCAgAGAgID/AAKA/oCAgAGAgID9gAKAgIAAAAABAAAAAAKAA4AACwAAMTUhESM1MzUzESEVAQCAgIABAIACAICA/QCAAAAAAAYAAAAAAoADgAAHAAsADwATABcAGwAAMREzFSE1MxEBNTMVPQEhFQE1MxUFETMRATUhFYABgID+AIABAP4AgAGAgP4AAYABAICA/wABAICAgICAAQCAgIABAP8AAQCAgAAAAAAHAAAAAAKAA4AAAwAHAAsADwATABcAGwAAMzUhFSU1MxUhETMRATUhFQE1MxUFETMRATUhFYABgP4AgAGAgP6AAQD+AIABgID+AAGAgICAgIABAP8AAQCAgAEAgICAAQD/AAEAgIAAAAMAAAAAAoADgAADAAcAEwAAEzUzFT0BMxUTESERMxUhESM1IRGAgICA/gCAAYCAAQACAICAgICA/YABAAEAgAGAgPyAAAAAAAQAAAAAAoADgAADAAcACwATAAAzNSEVJTUzFSERMxEBESEVIRUhFYABgP4AgAGAgP2AAoD+AAGAgICAgIABgP6AAYABgICAgAAAAAAFAAAAAAKAA4AAAwAHAA8AEwAXAAAzNSEVNREzESERMxUhFSEZATUzFT0BIRWAAYCA/YCAAYD+gIABAICAgAEA/wACAICA/wACAICAgICAAAMAAAAAAoADgAADAAcADwAAIREzGQE1MxU1ESEVIxEhEQEAgID+gIACgAGA/oABgICAgAEAgAEA/oAAAAcAAAAAAoADgAADAAcACwAPABMAFwAbAAAzNSEVJREzESERMxEBNSEVJREzESERMxEBNSEVgAGA/gCAAYCA/gABgP4AgAGAgP4AAYCAgIABAP8AAQD/AAEAgICAAQD/AAEA/wABAICAAAAAAAUAAAAAAoADgAADAAcACwATABcAADM1IRU9ATMVAREzEQE1ITUhETMRATUhFYABAID+AIABgP6AAYCA/gABgICAgICAAYABAP8A/wCAgAEA/gACAICAAAACAAAAAACAAwAAAwAHAAAxETMRAxEzEYCAgAEA/wACAAEA/wAAAAAAAgAA/4AAgAMAAAMABwAAFREzEQMRMxGAgICAAYD+gAKAAQD/AAAAAAcAAAAAAgADgAADAAcACwAPABMAFwAbAAAhNTMVJTUzFSU1MxUlNTMVPQEzFT0BMxU9ATMVAYCA/wCA/wCA/wCAgICAgICAgICAgICAgICAgICAgICAgIAAAAAAAgAAAIACgAKAAAMABwAAPQEhFQE1IRUCgP2AAoCAgIABgICAAAAAAAcAAAAAAgADgAADAAcACwAPABMAFwAbAAAxNTMVPQEzFT0BMxU9ATMVJTUzFSU1MxUlNTMVgICAgP8AgP8AgP8AgICAgICAgICAgICAgICAgICAgICAAAAGAAAAAAKAA4AAAwAHAAsADwATABcAACE1MxUDNTMVPQEzFQE1MxUFETMRATUhFQEAgICAgP4AgAGAgP4AAYCAgAEAgICAgIABAICAgAEA/wABAICAAAAABAAAAAADAAOAAAMABwAPABMAADM1IRUlETMRNxEhETMRMxEBNSEVgAIA/YCAgAEAgID9gAIAgICAAoD9gIABgP8AAYD+AAIAgIAAAAIAAAAAAoADgAALAA8AADERMxEhETMRIxEhGQE1IRWAAYCAgP6AAYADAP8AAQD9AAGA/oADAICAAAAAAAMAAAAAAoADgAADAAcAEwAAJREzEQM1MxUBESEVIRUhFSERIRUCAICAgP2AAgD+gAGA/oABgIABgP6AAgCAgP2AA4CAgID+gIAAAAAFAAAAAAKAA4AAAwAHAAsADwATAAAzNSEVPQEzFSERMxEBNTMVJTUhFYABgID9gIABgID+AAGAgICAgIACgP2AAgCAgICAgAACAAAAAAKAA4AAAwALAAAlETMRBREhFSERIRUCAID9gAIA/oABgIACgP2AgAOAgP2AgAAAAQAAAAACgAOAAAsAADERIRUhFSEVIREhFQKA/gABAP8AAgADgICAgP6AgAABAAAAAAKAA4AACQAAMREhFSEVIRUhEQKA/gABAP8AA4CAgID+AAAABAAAAAACgAOAAAMACQANABEAADM1IRU1ESE1IREhETMZATUhFYABgP8AAYD9gIACAICAgAGAgP4AAoD9gAKAgIAAAAABAAAAAAKAA4AACwAAMREzESERMxEjESERgAGAgID+gAOA/wABAPyAAgD+AAAAAAABAAAAAAGAA4AACwAAMTUzESM1IRUjETMVgIABgICAgAKAgID9gIAAAwAAAAACgAOAAAMABwALAAAzNSEVJTUzFSERMxGAAYD+AIABgICAgICAgAMA/QAABQAAAAACgAOAAAMABwALABMAFwAAIREzEQE1MxUDNTMVAREzESEVIREBNTMVAgCA/wCAgID+AIABAP8AAYCAAYD+gAGAgIABAICA/YADgP8AgP4AAwCAgAAAAAABAAAAAAKAA4AABQAAMREzESEVgAIAA4D9AIAAAwAAAAACgAOAAAMACwATAAABNTMVAREzFTMVIxEhESM1MzUzEQEAgP6AgICAAYCAgIACAICA/gADgICA/YACgICA/IAAAAAAAwAAAAACgAOAAAMACwATAAABNTMVAREzFTMVIxEhESM1MxEzEQEAgP6AgICAAYCAgIACAICA/gADgICA/YABgIABgPyAAAAABAAAAAACgAOAAAMABwALAA8AADM1IRUlETMRIREzEQE1IRWAAYD+AIABgID+AAGAgICAAoD9gAKA/YACgICAAAIAAAAAAoADgAADAA0AAAE1MxUBESEVIRUhFSERAgCA/YACAP6AAYD+gAKAgID9gAOAgICA/gAABgAAAAACgAOAAAMABwALAA8AEwAXAAAzNSEVMzUzFSU1MxUhETMRJREzEQE1IRWAAQCAgP8AgP4AgAGAgP4AAYCAgICAgICAAoD9gIACAP4AAgCAgAAAAAMAAAAAAoADgAADAAcAEQAAIREzEQM1MxUBESEVIRUhFSERAgCAgID9gAIA/oABgP6AAgD+AAKAgID9gAOAgICA/gAABgAAAAACgAOAAAMABwALAA8AEwAXAAAzNSEVJTUzFSERMxEBNSEVJTUzFT0BIRWAAYD+AIABgID+AAGA/gCAAgCAgICAgAGA/oABgICAgICAgICAAAAAAAEAAAAAAoADgAAHAAAhESE1IRUhEQEA/wACgP8AAwCAgP0AAAMAAAAAAoADgAADAAcACwAAMzUhFSURMxEhETMRgAGA/gCAAYCAgICAAwD9AAMA/QAAAAAFAAAAAAKAA4AAAwAHAAsADwATAAAhNTMVJREzETMRMxEBETMRIREzEQEAgP8AgICA/gCAAYCAgICAAQD/AAEA/wABAAIA/gACAP4AAAAAAAMAAAAAAoADgAADAAsAEwAAATUzFQERMxEzFSMVITUjNTMRMxEBAID+gICAgAGAgICAAQCAgP8AA4D9gICAgIACgPyAAAAAAAkAAAAAAoADgAADAAcACwAPABMAFwAbAB8AIwAAMREzESERMxEBNTMVMzUzFSU1MxUlNTMVMzUzFSU1MxUhNTMVgAGAgP4AgICA/wCA/wCAgID+AIABgIABgP6AAYD+gAGAgICAgICAgICAgICAgICAgIAABQAAAAACgAOAAAMABwALAA8AEwAAIREzEQE1MxUzNTMVJTUzFSE1MxUBAID/AICAgP4AgAGAgAKA/YACgICAgICAgICAgAAABQAAAAACgAOAAAUACQANABEAFwAAMREzFSEVATUzFT0BMxU9ATMVPQEhNSERgAH//gGAgID+AAKAAQCAgAEAgICAgICAgICAgID/AAAAAAABAAAAAAGAA4AABwAAMREhFSERIRUBgP8AAQADgID9gIAAAAAFAAAAAAKAA4AAAwAHAAsADwATAAAhNTMVJREzEQE1MxUlETMRATUzFQIAgP8AgP8AgP8AgP8AgICAgAEA/wABAICAgAEA/wABAICAAAAAAAEAAAAAAYADgAAHAAAxNSERITUhEQEA/wABgIACgID8gAAAAAUAAAIAAoADgAADAAcACwAPABMAABE1MxUhNTMVJTUzFTM1MxUlNTMVgAGAgP4AgICA/wCAAgCAgICAgICAgICAgIAAAQAAAAACgACAAAMAADE1IRUCgICAAAAAAgAAAgABAAOAAAMABwAAEzUzFSURMxGAgP8AgAIAgICAAQD/AAAAAAMAAAAAAoACgAADAA0AEQAAPQEzHQE1ITUhNSE1MxEBNSEVgAGA/oABgID+AAGAgICAgICAgID+AAIAgIAAAAADAAAAAAKAA4AAAwAHABEAACURMxEBNSEVAREzETMVIxEhFQIAgP6AAQD+AICAgAGAgAGA/oABgICA/gADgP6AgP8AgAAAAAAFAAAAAAKAAoAAAwAHAAsADwATAAAzNSEVPQEzFSERMxEBNTMVJTUhFYABgID9gIABgID+AAGAgICAgIABgP6AAQCAgICAgAADAAAAAAKAA4AAAwAHABEAADURMxkBNSEVATUhESM1MxEzEYABAP8AAYCAgICAAYD+gAGAgID+AIABAIABgPyAAAAAAAMAAAAAAoACgAADAA0AEQAAMzUhFSURMxUhNTMRIRURNSEVgAIA/YCAAYCA/gABgICAgAGAgID/AIABgICAAAACAAAAAAIAA4AACwAPAAAzESM1MzUzFSEVIRkBNSEVgICAgAEA/wABAAIAgICAgP4AAwCAgAAAAAMAAP+AAoACgAADAAcAEQAAFTUhFQERMxEBNSE1IREhNSERAgD+AIABgP6AAYD+gAIAgICAAYABAP8A/wCAgAEAgP2AAAAAAAMAAAAAAoADgAADAAcADwAAIREzEQE1IRUBETMRMxUjEQIAgP6AAQD+AICAgAIA/gACAICA/gADgP6AgP6AAAACAAAAAACAA4AAAwAHAAAxETMRAzUzFYCAgAKA/YADAICAAAAEAAD/gAKAA4AAAwAHAAsADwAAFzUhFSURMxEhETMRAzUzFYABgP4AgAGAgICAgICAgAEA/wACgP2AAwCAgAAABQAAAAACAAOAAAMABwALAA8AFwAAITUzFSU1MxUDNTMVPQEzFQERMxEzFSMRAYCA/wCAgICA/gCAgICAgICAgAEAgICAgID+AAOA/gCA/wAAAAAAAgAAAAABAAOAAAMABwAAMzUzFSURMxGAgP8AgICAgAMA/QAABAAAAAACgAKAAAMABwANABEAAAERMxETETMRIREhFSMRATUzFQEAgICA/YABAIABAIABAAEA/wD/AAIA/gACgID+AAIAgIAAAgAAAAACgAKAAAMACQAAIREzESERIRUhEQIAgP2AAgD+gAIA/gACgID+AAAEAAAAAAKAAoAAAwAHAAsADwAAMzUhFSURMxEhETMRATUhFYABgP4AgAGAgP4AAYCAgIABgP6AAYD+gAGAgIAAAwAA/4ACgAKAAAMADwATAAABETMRAREzFTMVIxUhFSEREzUhFQIAgP2AgICAAYD+gIABAAEAAQD/AP6AAwCAgICA/wACgICAAAAAAAMAAP+AAoACgAADAAcAEwAAGQEzGQE1IRUTESE1ITUjNTM1MxGAAQCA/oABgICAgAEAAQD/AAEAgID9gAEAgICAgP0AAAAAAAMAAAAAAoACgAADAAsADwAAATUzFQERMxUzFSMREzUhFQIAgP2AgICAgAEAAYCAgP6AAoCAgP6AAgCAgAAAAAAFAAAAAAKAAoAAAwAHAAsADwATAAAxNSEVPQEzFSU1IRUlNTMVPQEhFQIAgP4AAYD+AIACAICAgICAgICAgICAgICAAAIAAAAAAYADgAADAA8AACE1MxUlESM1MxEzETMVIxEBAID/AICAgICAgICAAYCAAQD/AID+gAAAAgAAAAACgAKAAAMACQAANREzERU1IREzEYABgICAAgD+AICAAgD9gAAAAAAFAAAAAAKAAoAAAwAHAAsADwATAAAhNTMVJTUzFTM1MxUlETMRIREzEQEAgP8AgICA/gCAAYCAgICAgICAgIABgP6AAYD+gAACAAAAAAKAAoAAAwANAAA1ETMRFTUzETMRMxEzEYCAgICAgAIA/gCAgAEA/wACAP2AAAAACQAAAAACgAKAAAMABwALAA8AEwAXABsAHwAjAAAxNTMVITUzFSU1MxUzNTMVJTUzFSU1MxUzNTMVJTUzFSE1MxWAAYCA/gCAgID/AID/AICAgP4AgAGAgICAgICAgICAgICAgICAgICAgICAgIAAAAMAAP+AAoACgAADAAcADwAAFTUhFQERMxEBNSE1IREzEQIA/gCAAYD+gAGAgICAgAGAAYD+gP8AgIABgP2AAAADAAAAAAKAAoAABwALABMAADE1MzUzFSEVATUzFT0BITUhFSMVgIABgP6AgP6AAoCAgICAgAEAgICAgICAgAAABQAAAAACAAOAAAMABwALAA8AEwAAITUhFSURMxEBNTMVNREzGQE1IRUBAAEA/oCA/wCAgAEAgICAAQD/AAEAgICAAQD/AAEAgIAAAAIAAAAAAIADgAADAAcAADERMxEDETMRgICAAYD+gAIAAYD+gAAAAAAFAAAAAAIAA4AAAwAHAAsADwATAAAxNSEVNREzGQE1MxUlETMRATUhFQEAgID/AID+gAEAgICAAQD/AAEAgICAAQD/AAEAgIAAAAAABAAAAoADAAOAAAMABwALAA8AABE1MxUhNSEVJTUhFSE1MxWAAQABAP4AAQABAIACgICAgICAgICAgAAAAgAAAAAAgAMAAAMABwAAMREzEQM1MxWAgIACAP4AAoCAgAAABAAAAAACgAOAAAMABwALAB8AAAE1MxUhETMRATUzFQE1IzUzESM1MzUzFTMVIxEzFSMVAgCA/YCAAYCA/oCAgICAgICAgIABAICAAYD+gAEAgID+AICAAYCAgICA/oCAgAAAAAMAAAAAAoADgAAPABMAFwAAMTUzESM1MxEzESEVIREhFQM1MxUlNSEVgICAgAEA/wABgICA/oABAIABAIABAP8AgP8AgAKAgICAgIAAAAAACAAAAIACAAMAAAMABwALAA8AEwAXABsAHwAAPQEzFSE1MxUlNSEVJTUzFSE1MxUlNSEVJTUzFSE1MxWAAQCA/oABAP6AgAEAgP6AAQD+gIABAICAgICAgICAgICAgICAgICAgICAgIAAAAAABQAAAAACgAOAABMAFwAbAB8AIwAAITUjNTM1IzUzNTMVMxUjFTMVIxUBNTMVMzUzFSU1MxUhNTMVAQCAgICAgICAgID/AICAgP4AgAGAgICAgICAgICAgIACgICAgICAgICAgAAAAAACAAAAAACAA4AAAwAHAAAxETMRAxEzEYCAgAGA/oACAAGA/oAAAAAACAAAAAACAAOAAAMABwALAA8AEwAXABsAHwAAMTUhFT0BMxUlNSEVJTUzFSE1MxUlNSEVJTUzFT0BIRUBgID+gAEA/oCAAQCA/oABAP6AgAGAgICAgICAgICAgICAgICAgICAgICAgAACAAADAAKAA4AAAwAHAAARNSEVMzUhFQEAgAEAAwCAgICAAAADAAAAAAMAAoAADQARABsAADM1IxEzETMVMzUzFTMVNREzESURIzUhFSMVIxWAgICAgICAgP4AgAIAgICAAYD/AICAgICAAYD+gIABAICAgIAAAAABAAACAAGAA4AACQAAETUzNSM1IRUzEYCAAQCAAgCAgICA/wAAAAAACgAAAAACgAKAAAMABwALAA8AEwAXABsAHwAjACcAACE1MxUzNTMVJTUzFTM1MxUlNTMVMzUzFSU1MxUzNTMVJTUzFTM1MxUBAICAgP4AgICA/gCAgID/AICAgP8AgICAgICAgICAgICAgICAgICAgICAgICAgICAAAAAAAEAAAAAAoABgAAFAAAhESE1IRECAP4AAoABAID+gAAAAQAAAgACgAKAAAMAABE1IRUCgAIAgIAAAwAAAQADAAOAAAMABwAZAAABNSMVIREzERU1MxEzNSE1IRUjFTM1MxEjFQIAgP6AgICA/wACAICAgIABgICAAYD+gICAAQCAgICAgP6AgAABAAADAAKAA4AAAwAAETUhFQKAAwCAgAAEAAACAAGAA4AAAwAHAAsADwAAEzUzFSU1MxUzNTMVJTUzFYCA/wCAgID/AIACAICAgICAgICAgIAAAAACAAAAAAMAA4AAAwAPAAAxNSEVAREhNSERIREhFSERAwD+AP8AAQABAAEA/wCAgAEAAQCAAQD/AID/AAABAAABAAIAA4AAEQAAGQEzNTM1ITUhFTMVIxUjFSEVgID/AAGAgICAAQABAAEAgICAgICAgIAAAAEAAAEAAgADgAAPAAARNSE1IzUzNSE1IRUzESMVAQCAgP8AAYCAgAEAgICAgICA/oCAAAACAAACAAEAA4AAAwAHAAARNTMVNREzEYCAAgCAgIABAP8AAAABAAAAgAOAA4AADwAAPQEzESERIREhESMVIRUjFYABAAEAAQCA/oCAgIACgP6AAYD+gICAgAAAAAIAAAAABAADgAADABEAAAERIxETESE1IxEzNSERIREjEQGAgID/AICAA4D/AIACAAEA/wD+AAGAgAEAgPyAAwD9AAAAAQAAAQABAAGAAAMAABE1IRUBAAEAgIAAAwAAAAABgAIAAAMABwANAAAxNSEVPQEzFSU1MzUzEQEAgP6AgICAgICAgICAgP8AAAAAAAEAAAIAAQADgAAFAAATESM1IRGAgAEAAgABAID+gAAABAAAAgABgAOAAAMABwALAA8AABM1MxUlNTMVMzUzFSU1MxWAgP8AgICA/wCAAgCAgICAgICAgICAAAAACgAAAAACgAKAAAMABwALAA8AEwAXABsAHwAjACcAADE1MxUzNTMVJTUzFTM1MxUlNTMVMzUzFSU1MxUzNTMVJTUzFTM1MxWAgID/AICAgP8AgICA/gCAgID+AICAgICAgICAgICAgICAgICAgICAgICAgICAgAAABwAAAAACgAOAAAMABwANABEAFQAZAB0AADE1MxU1ETMRBTUjESERATUzFTURMxElETMRJTUzFYCAAQCAAQD+gICA/gCAAYCAgICAAQD/AICAAQD+gAGAgICAAQD/AIABAP8AgICAAAAIAAAAAAKAA4AAAwAJAA0AEQAVABkAHQAhAAAxNTMVIREzFTMVJREzESU1MxUlNTMVNREzESURMxElNTMVgAEAgID+AIABAID+gICA/gCAAYCAgIABAICAgAEA/wCAgICAgICAAQD/AIABAP8AgICAAAAAAAUAAAAAAoADgAADAAkADQAbAB8AADE1MxUhNSMRIREBETMRAREjNTM1IxEhETMVIxEBNTMVgAGAgAEA/wCA/oCAgIABAICAAQCAgICAAQD+gAIAAQD/AP6AAQCAgAEA/oCA/wACgICAAAAAAAYAAAAAAoADgAADAAcACwAPABMAFwAAMzUhFT0BMxUhETMZATUzFT0BMxUDNTMVgAGAgP2AgICAgICAgICAgAEA/wABAICAgICAAQCAgAAABAAAAAACgAUAAAsADwATABcAADERMxEhETMRIxEhGQE1IRUBNTMVJTUzFYABgICA/oABgP8AgP8AgAMA/wABAP0AAYD+gAMAgIABAICAgICAAAAABAAAAAACgAUAAAsADwATABcAADERMxEhETMRIxEhGQE1IRUBNTMVPQEzFYABgICA/oABgP8AgIADAP8AAQD9AAGA/oADAICAAQCAgICAgAAFAAAAAAKABQAACwAPABMAFwAbAAAxETMRIREzESMRIRkBNSEVATUzFTM1MxUlNTMVgAGAgID+gAGA/oCAgID/AIADAP8AAQD9AAGA/oADAICAAQCAgICAgICAAAMAAAAAAoAEgAALAA8AEwAAMREzESERMxEjESEZATUhFQE1IRWAAYCAgP6AAYD+gAGAAwD/AAEA/QABgP6AAwCAgAEAgIAAAAQAAAAAAoAEgAALAA8AEwAXAAAxETMRIREzESMRIRkBNSEVATUhFTM1IRWAAYCAgP6AAYD+AAEAgAEAAwD/AAEA/QABgP6AAwCAgAEAgICAgAAAAAMAAAAAAoAEgAALABMAFwAAMREzESERMxEjESEZAjMVMzUzEQE1MxWAAYCAgP6AgICA/wCAAwD/AAEA/QABgP6AAwABAICA/wABAICAAAAAAQAAAAACgAOAABUAADERMxUzNSM1IRUhFTMVIxEhFSERIxGAgIACAP8AgIABAP6AgAMAgICAgICA/oCAAgD+AAAAAAAHAAD/AAKAA4AABwALAA8AEwAXABsAHwAAATUjNSEVMxUDNTMVJTUhFT0BMxUhETMRATUzFSU1IRUBgIABAICAgP4AAYCA/YCAAYCA/gABgP8AgICAgAEAgICAgICAgIACAP4AAYCAgICAgAADAAAAAAKABQAACwAPABMAADERIRUhFSEVIREhFQE1MxUlNTMVAoD+AAEA/wACAP6AgP8AgAOAgICA/oCABACAgICAgAAAAAADAAAAAAKABQAACwAPABMAADERIRUhFSEVIREhFQE1MxU9ATMVAoD+AAEA/wACAP6AgIADgICAgP6AgAQAgICAgIAAAAQAAAAAAoAFAAALAA8AEwAXAAAxESEVIRUhFSERIRUBNTMVMzUzFSU1MxUCgP4AAQD/AAIA/gCAgID/AIADgICAgP6AgAQAgICAgICAgAAAAwAAAAACgASAAAsADwATAAAxESEVIRUhFSERIRUBNSEVMzUhFQKA/gABAP8AAgD9gAEAgAEAA4CAgID+gIAEAICAgIAAAAAAAwAAAAABAAQAAAMABwALAAAzETMRAzUzFSU1MxWAgICA/wCAAoD9gAMAgICAgIAAAwCAAAABgAQAAAMABwALAAAzETMRAzUzFT0BMxWAgICAgAKA/YADAICAgICAAAAABAAAAAABgAQAAAMABwALAA8AADMRMxEBNTMVMzUzFSU1MxWAgP8AgICA/wCAAoD9gAMAgICAgICAgAAAAwAAAAABgAOAAAMABwALAAAzETMRATUzFTM1MxWAgP8AgICAAoD9gAMAgICAgAAAAv+AAAACgAOAAAMAEwAAJREzEQURIzUzESEVIREhFSERIRUCAID9gICAAgD+gAEA/wABgIACgP2AgAGAgAGAgP8AgP8AgAAABAAAAAACgASAAAMACwATABcAAAE1MxUBETMVMxUjESERIzUzETMRATUhFQEAgP6AgICAAYCAgID+AAGAAgCAgP4AA4CAgP2AAYCAAYD8gAQAgIAABgAAAAACgAUAAAMABwALAA8AEwAXAAAzNSEVJREzESERMxEBNSEVATUzFSU1MxWAAYD+AIABgID+AAGA/wCA/wCAgICAAoD9gAKA/YACgICAAQCAgICAgAAAAAAGAAAAAAKABQAAAwAHAAsADwATABcAADM1IRUlETMRIREzEQE1IRUBNTMVPQEzFYABgP4AgAGAgP4AAYD/AICAgICAAoD9gAKA/YACgICAAQCAgICAgAAABgAAAAACgAUAAAMABwALAA8AFQAZAAAzNSEVJREzESERMxEBNTMVAzUhETMRATUzFYABgP4AgAGAgP4AgIABAID/AICAgIACgP2AAoD9gAOAgID/AIABAP6AAYCAgAAABQAAAAACgASAAAMABwALAA8AEwAAMzUhFSURMxEhETMRATUhFQE1IRWAAYD+AIABgID+AAGA/oABgICAgAKA/YACgP2AAoCAgAEAgIAAAAAGAAAAAAKABIAAAwAHAAsADwATABcAADM1IRUlETMRIREzEQE1IRUBNSEVMzUhFYABgP4AgAGAgP4AAYD+AAEAgAEAgICAAoD9gAKA/YACgICAAQCAgICAAAAAAAkAAACAAoADAAADAAcACwAPABMAFwAbAB8AIwAAPQEzFSE1MxUlNTMVMzUzFSU1MxUlNTMVMzUzFSU1MxUhNTMVgAGAgP4AgICA/wCA/wCAgID+AIABgICAgICAgICAgICAgICAgICAgICAgICAgAAFAAAAAAKAA4AAAwAHAA8AFwAbAAAzNSEVATUzFQERMxEzFSMVIREjNTM1MxEBNSEVgAGA/wCA/oCAgIABgICAgP4AAYCAgAGAgID/AAKA/oCAgAGAgID9gAKAgIAAAAAFAAAAAAKABIAAAwAHAAsADwATAAAzNSEVJREzESERMxEBNTMVJTUzFYABgP4AgAGAgP6AgP8AgICAgAMA/QADAP0AAwCAgICAgAAABQAAAAACgASAAAMABwALAA8AEwAAMzUhFSURMxEhETMRATUzFT0BMxWAAYD+AIABgID+gICAgICAAwD9AAMA/QADAICAgICAAAAAAAQAAAAAAoAEgAADAAcACwAPAAAzNSEVJREzESERMxEBNSEVgAGA/gCAAYCA/gABgICAgAMA/QADAP0AA4CAgAAFAAAAAAKABIAAAwAHAAsADwATAAAzNSEVJREzESERMxEBNSEVMzUhFYABgP4AgAGAgP2AAQCAAQCAgIADAP0AAwD9AAOAgICAgAAABwAAAAACgASAAAMABwALAA8AEwAXABsAACERMxEBNTMVMzUzFSU1MxUhNTMVJTUzFT0BMxUBAID/AICAgP4AgAGAgP6AgIACgP2AAoCAgICAgICAgICAgICAgIAAAAAAAgAAAAACAAOAAAMADwAAAREzEQERMxUhFSERIRUhFQGAgP4AgAEA/wABAP8AAQABgP6A/wADgICA/oCAgAAAAAQAAAAAAoADgAAFAAkADQATAAAhNSERMxEBNTMVNREzEQERIRUhEQEAAQCA/wCAgP2AAgD+gIABAP6AAYCAgIABAP8A/gADgID9AAAFAAAAAAKAA4AAAwAHAA0AEQAVAAAzNSEVJTUzFT0BITUzEQE1IRUBNSEVgAIA/YCAAYCA/gABgP4AAQCAgICAgICAgP8AAQCAgAEAgIAAAAQAAAAAAoADgAADAA0AEQAVAAA9ATMdATUhNSE1ITUzEQE1IRUDNSEVgAGA/oABgID+AAGAgAEAgICAgICAgID+AAIAgIABAICAAAAEAAAAAAKAA4AAAwANABEAFQAAPQEzHQE1ITUhNSE1MxEBNSEVATUzFYABgP6AAYCA/gABgP8AgICAgICAgICA/gACAICAAQCAgAAABAAAAAACgAOAAAMADQARABUAAD0BMx0BNSE1ITUhNTMRATUhFQE1IRWAAYD+gAGAgP4AAYD+gAGAgICAgICAgID+AAIAgIABAICAAAUAAAAAAoADgAADAA0AEQAVABkAAD0BMx0BNSE1ITUhNTMRATUhFQE1MxUzNTMVgAGA/oABgID+AAGA/oCAgICAgICAgICAgP4AAgCAgAEAgICAgAAAAAAGAAAAAAKAA4AAAwANABEAFQAZAB0AAD0BMx0BNSE1ITUhNTMRATUhFSU1MxUhNTMVJTUhFYABgP6AAYCA/gABgP4AgAGAgP4AAYCAgICAgICAgP4AAgCAgICAgICAgICAAAAABAAAAAACgAKAAAMAFQAZAB0AAD0BMx0BNTM1IzUzNTMVMzUzESEVIRUBNTMVMzUzFYCAgICAgID/AAEA/gCAgICAgICAgICAgICA/wCAgAIAgICAgAAAAAgAAP8AAoADAAADAAcACwAPABMAFwAbAB8AABE1IRU9ASEVPQEzFSU1IRU9ATMVIREzEQE1MxUlNSEVAQABAID+AAGAgP2AgAGAgP4AAYD/AICAgICAgICAgICAgICAAYD+gAEAgICAgIAAAAQAAAAAAoADgAADAA0AEQAVAAAzNSEVJREzFSE1MxEhFRE1IRUBNSEVgAIA/YCAAYCA/gABgP4AAQCAgIABgICA/wCAAYCAgAEAgIAAAAAABAAAAAACgAOAAAMADQARABUAADM1IRUlETMVITUzESEVETUhFQM1IRWAAgD9gIABgID+AAGAgAEAgICAAYCAgP8AgAGAgIABAICAAAQAAAAAAoADgAADAA0AEQAVAAAzNSEVJREzFSE1MxEhFRE1IRUBNTMVgAGA/gCAAYCA/gABgP8AgICAgAGAgID/AIABgICAAQCAgAAFAAAAAAKAA4AAAwANABEAFQAZAAAzNSEVJREzFSE1MxEhFRE1IRUBNSEVMzUhFYABgP4AgAGAgP4AAYD+AAEAgAEAgICAAYCAgP8AgAGAgIABAICAgIAAAgAAAAABAAQAAAMABwAAMxEzEQERMxGAgP8AgAKA/YADAAEA/wAAAAIAAAAAAQAEAAADAAcAADERMxkCMxGAgAKA/YADAAEA/wAAAAMAAAAAAIAEgAADAAcACwAAMREzEQM1MxUDNTMVgICAgIACgP2AAwCAgAEAgIAAAAQAAAAAAYAEgAADAAcACwAPAAAzETMRAzUzFQE1MxUzNTMVgICAgP8AgICAAoD9gAMAgIABAICAgIAAAAMAAAAAAoAEAAADAAcAFwAANREzGQE1MxUDNSERITUhNSE1MzUzFTMRgICAAYD+gAGA/wCAgICAAYD+gAMAgID8gIABgICAgICA/IAAAAAAAwAAAAACgAOAAAMACQANAAAhETMRIREhFSEZATUhFQIAgP2AAgD+gAGAAgD+AAKAgP4AAwCAgAAFAAAAAAKAA4AAAwAHAAsADwATAAAzNSEVJREzESERMxEBNSEVATUhFYABgP4AgAGAgP4AAYD+AAEAgICAAYD+gAGA/oABgICAAQCAgAAAAAUAAAAAAoADgAADAAcACwAPABMAADM1IRUlETMRIREzEQE1IRUDNSEVgAGA/gCAAYCA/gABgIABAICAgAGA/oABgP6AAYCAgAEAgIAAAAAABgAAAAACgAOAAAMABwALAA8AEwAXAAAzNSEVJREzESERMxEBNSEVPQEzFSU1IRWAAYD+AIABgID+AAGAgP4AAYCAgIABgP6AAYD+gAGAgICAgICAgIAAAAUAAAAAAoADgAADAAcACwAPABMAADM1IRUlETMRIREzEQE1IRUBNSEVgAGA/gCAAYCA/gABgP6AAYCAgIABgP6AAYD+gAGAgIABAICAAAAABgAAAAACgAOAAAMABwALAA8AEwAXAAAzNSEVJREzESERMxEBNSEVATUhFTM1IRWAAYD+AIABgID+AAGA/gABAIABAICAgAGA/oABgP6AAYCAgAEAgICAgAAAAAADAAAAAAMAA4AAAwAHAAsAACERIREBNSEVAREhEQEAAQD+AAMA/gABAAEA/wABgICAAQABAP8AAAMAAAAAAoACgAADAA0AFwAAATUzFQE1IxEzETMVIRU1ESM1ITUhFTMRAQCA/wCAgIABAID/AAGAgAEAgID/AIABgP8AgICAAQCAgID+gAAAAwAAAAACgAOAAAMACQANAAA1ETMRFTUhETMRATUhFYABgID9gAEAgAIA/gCAgAIA/YADAICAAAADAAAAAAKAA4AAAwAJAA0AADURMxEVNSERMxEBNSEVgAGAgP8AAQCAAgD+AICAAgD9gAMAgIAAAAMAAAAAAoADgAADAAkADQAANREzERU1IREzEQE1MxWAAYCA/oCAgAIA/gCAgAIA/YADAICAAAAABAAAAAACgAOAAAMACQANABEAADURMxEVNSERMxEBNTMVMzUzFYABgID+AICAgIACAP4AgIACAP2AAwCAgICAAAUAAP+AAoADgAADAAcADwATABcAABU1IRUBETMRATUhNSERMxEBNTMVPQEzFQIA/gCAAYD+gAGAgP6AgICAgIABgAGA/oD/AICAAYD9gAKAgICAgIAAAAACAAD/gAGAAwAAAwAPAAABNTMVAREzETMVIxUzFSMRAQCA/oCAgICAgAEAgID+gAOA/wCAgID/AAAAAAAFAAD/gAKAA4AAAwAHAA8AEwAXAAAVNSEVAREzEQE1ITUhETMRATUzFTM1MxUCAP4AgAGA/oABgID+AICAgICAgAGAAYD+gP8AgIABgP2AAwCAgICAAAAABwAAAAACgASAAAMABwALAA8AEwAXABsAACERMxEBNTMVMzUzFSU1MxUhNTMVATUhFTM1IRUBAID/AICAgP4AgAGAgP2AAQCAAQACgP2AAoCAgICAgICAgIABAICAgIAAAwAAAAACgAOAAAMACwARAAAhNSEVNREjNTMRMxEFESEVIREBAAEAgICA/YACAP6AgICAAQCAAQD9gIADgID9AAAAAAABAAABgAKAAgAAAwAAETUhFQKAAYCAgAACAAACAAEAA4AAAwAHAAARNTMVNREzEYCAAgCAgIABAP8AAAACAAACAAEAA4AAAwAHAAARNTMVNREzEYCAAgCAgIABAP8AAAACAAAAAAEAAYAAAwAHAAAxNTMVNREzEYCAgICAAQD/AAAAAAACAAACAAEAA4AAAwAHAAATNTMVJREzEYCA/wCAAgCAgIABAP8AAAAABAAAAgACAAOAAAMABwALAA8AABE1MxUzNTMVJREzETMRMxGAgID/AICAgAIAgICAgIABAP8AAQD/AAAABAAAAgACAAOAAAMABwALAA8AABE1MxUzNTMVJREzETMRMxGAgID/AICAgAIAgICAgIABAP8AAQD/AAAABAAAAAACAAGAAAMABwALAA8AADE1MxUzNTMVJREzETMRMxGAgID/AICAgICAgICAAQD/AAEA/wAAAAAAAQAAAAACgAOAAAsAACERITUhETMRIRUhEQEA/wABAIABAP8AAgCAAQD/AID+AAAAAQAAAQABgAKAAAsAABM1IzUzNTMVMxUjFYCAgICAgAEAgICAgICAAAMAAAAAAoABAAADAAcACwAAMREzETMRMxEzETMRgICAgIABAP8AAQD/AAEA/wAAAAUAAACAAYADAAADAAcACwAPABMAACU1MxUlNTMVJTUzFT0BMxU9ATMVAQCA/wCA/wCAgICAgICAgICAgICAgICAgIAABQAAAIABgAMAAAMABwALAA8AEwAAPQEzFT0BMxU9ATMVJTUzFSU1MxWAgID/AID/AICAgICAgICAgICAgICAgIAAAAABAAAAAAKAA4AAFwAAITUjNSMRMzUzNSEVIRUjFSEVIRUzFSEVAQCAgICAAYD/AIABgP6AgAEAgIABgICAgICAgICAgAAAAAABAAACAAMAA4AADwAAExEjNSEVMzUzFTMRITUjFYCAAYCAgID/AIACAAEAgICAgP8AgIAAAwAAAAACgAOAAA0AEQAVAAAzESM1MzUzFSERIxEhGQE1MxUzNTMVgICAgAGAgP8AgICAAgCAgID9gAIA/gADAICAgIAAAAAAAgAAAAACgAOAAAsAEQAAMxEjNTM1MxUzFSMRIREhNSERgICAgICAAQD/AAGAAgCAgICA/gADAID8gAAAAAAeAW4AAQAAAAAAAAAWAC4AAQAAAAAAAQALAF0AAQAAAAAAAgAHAHkAAQAAAAAAAwALAJkAAQAAAAAABAATAM0AAQAAAAAABQALAPkAAQAAAAAABgALAR0AAQAAAAAACAAMAUMAAQAAAAAACQAMAWoAAQAAAAAACgABAXsAAQAAAAAACwAaAbMAAQAAAAAADAAaAgQAAQAAAAAADQAoAnEAAQAAAAAADgAuAvgAAQAAAAAAEwApA3sAAwABBAkAAAAsAAAAAwABBAkAAQAWAEUAAwABBAkAAgAOAGkAAwABBAkAAwAWAIEAAwABBAkABAAmAKUAAwABBAkABQAWAOEAAwABBAkABgAWAQUAAwABBAkACAAYASkAAwABBAkACQAYAVAAAwABBAkACgACAXcAAwABBAkACwA0AX0AAwABBAkADAA0Ac4AAwABBAkADQBQAh8AAwABBAkADgBcApoAAwABBAkAEwBSAycAQwBvAHAAeQByAGkAZwBoAHQAIABBAG4AZAByAGUAdwAgAFQAeQBsAGUAcgAAQ29weXJpZ2h0IEFuZHJldyBUeWxlcgAATQBpAG4AZQBjAHIAYQBmAHQAaQBhAABNaW5lY3JhZnRpYQAAUgBlAGcAdQBsAGEAcgAAUmVndWxhcgAATQBpAG4AZQBjAHIAYQBmAHQAaQBhAABNaW5lY3JhZnRpYQAATQBpAG4AZQBjAHIAYQBmAHQAaQBhACAAUgBlAGcAdQBsAGEAcgAATWluZWNyYWZ0aWEgUmVndWxhcgAAVgBlAHIAcwBpAG8AbgAgADEALgAwAABWZXJzaW9uIDEuMAAATQBpAG4AZQBjAHIAYQBmAHQAaQBhAABNaW5lY3JhZnRpYQAAQQBuAGQAcgBlAHcAIABUAHkAbABlAHIAAEFuZHJldyBUeWxlcgAAQQBuAGQAcgBlAHcAIABUAHkAbABlAHIAAEFuZHJldyBUeWxlcgAACgAACgAAaAB0AHQAcAA6AC8ALwB3AHcAdwAuAGEAbgBkAHIAZQB3AHQAeQBsAGUAcgAuAG4AZQB0AABodHRwOi8vd3d3LmFuZHJld3R5bGVyLm5ldAAAaAB0AHQAcAA6AC8ALwB3AHcAdwAuAGEAbgBkAHIAZQB3AHQAeQBsAGUAcgAuAG4AZQB0AABodHRwOi8vd3d3LmFuZHJld3R5bGVyLm5ldAAAQwByAGUAYQB0AGkAdgBlACAAQwBvAG0AbQBvAG4AcwAgAEEAdAB0AHIAaQBiAHUAdABpAG8AbgAgAFMAaABhAHIAZQAgAEEAbABpAGsAZQAAQ3JlYXRpdmUgQ29tbW9ucyBBdHRyaWJ1dGlvbiBTaGFyZSBBbGlrZQAAaAB0AHQAcAA6AC8ALwBjAHIAZQBhAHQAaQB2AGUAYwBvAG0AbQBvAG4AcwAuAG8AcgBnAC8AbABpAGMAZQBuAHMAZQBzAC8AYgB5AC0AcwBhAC8AMwAuADAALwAAaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvYnktc2EvMy4wLwAARgBpAHYAZQAgAGIAaQBnACAAcQB1AGEAYwBrAGkAbgBnACAAegBlAHAAaAB5AHIAcwAgAGoAbwBsAHQAIABtAHkAIAB3AGEAeAAgAGIAZQBkAABGaXZlIGJpZyBxdWFja2luZyB6ZXBoeXJzIGpvbHQgbXkgd2F4IGJlZAAAAAIAAAAAAAAAYgAzAAAAAAAAAAAAAAAAAAAAAAAAAAAA1AAAAQIBAwADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAowCEAIUAvQCWAOgAhgCOAIsAnQCpAKQBBACKANoAgwCTAQUBBgCNAQcAiADDAN4BCACeAKoA9QD0APYAogCtAMkAxwCuAGIAYwCQAGQAywBlAMgAygDPAMwAzQDOAOkAZgDTANAA0QCvAGcA8ACRANYA1ADVAGgA6wDtAIkAagBpAGsAbQBsAG4AoABvAHEAcAByAHMAdQB0AHYAdwDqAHgAegB5AHsAfQB8ALgAoQB/AH4AgACBAOwA7gC6ALsBCQCzALYAtwDEAQoAtAC1AMUAggCHAKsAvgC/AQsAjAEMAQ0GZ2x5cGgxBmdseXBoMgd1bmkwMEFEB3VuaTAwQjIHdW5pMDBCMwd1bmkwMEI1B3VuaTAwQjkHdW5pMUU5RQ1xdW90ZXJldmVyc2VkBEV1cm8HdW5pRkIwMQd1bmlGQjAyAAAAAAH//wACAAEAAAAOAAAAGAAgAAAAAgABAAEA0wABAAQAAAACAAAAAQAAAAEAAAAAAAEAAAAAyYlvMQAAAADK8HqtAAAAAMtPFqk= ";
var ctx = com.mojang.minecraftpe.MainActivity.currentMainActivity.get();
var sdCard = android.os.Environment.getExternalStorageDirectory();
var Color = android.graphics.Color.BLUE;
var show = false;
var switched = false;
var switched2 = false;
var switched3 = false;
var switched5 = false;
var guide4 = false;
var clickThunder = false;
var telOn = false;
var punchOn = false;
var godMode = false;
var paused = false;
var clickSound = "random.click";
var punchRadius = 3;
var textSize = 20;
var debugTextSize = 12;
var accelSpeed = 2;
var bounceSpeed = 1;
var compass = "";
var modFont;
var GUI;
var menu;
var exitUI;
var info;
var shot;
var FunMode;
var netAccess;

function dip2px(dips){

return Math.ceil(dips * ctx.getResources().getDisplayMetrics().density);
}

function newLevel(){

Base64Decode(android.util.Base64.decode(font, 0), modPath + "minecraft.ttf");

if(ModPE.readData("Bounce") >= 1){
bounceSpeed = ModPE.readData("Bounce");
}
if(ModPE.readData("MenuTextSize") >= 1){
textSize = ModPE.readData("MenuTextSize");
}
if(ModPE.readData("DebugSize") >= 1){
debugTextSize = ModPE.readData("DebugSize");
}
if(ModPE.readData("Accel") >= 1){
accelSpeed = ModPE.readData("Accel");
}
if(ModPE.readData("PunchRadius") >= 1){
punchRadius = ModPE.readData("PunchRadius");
}
if(ModPE.readData("ExplodeArrowRadius") >= 1){
explodeRadius = ModPE.readData("ExplodeArrowRadius");
}

firstButton();

ctx.runOnUiThread(new java.lang.Runnable(){ run: function(){

if(!bounceSpeed || !textSize || !debugTextSize || !accelSpeed || !punchRadius) new android.widget.Toast.makeText(ctx,new android.text.Html.fromHtml("<b><font color=#FF0000>[Mostly Needed Tool Mod] Go To Settings And Configure Some No Value Their First.</b>"),1).show();
}});

modFont = new android.graphics.Typeface.createFromFile(modPath + "minecraft.ttf");

}

function firstButton(){

ctx.runOnUiThread(new java.lang.Runnable({ run: function(){

var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(1);

var menuBtn = new android.widget.Button(ctx);
menuBtn.setText('*M*N*T*');
menuBtn.setTextSize(textSize);
menuBtn.setTextColor(Color);
menuBtn.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
openMenu();
exit();
GUI.dismiss();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(menuBtn);

GUI = new android.widget.PopupWindow(layout, android.widget.RelativeLayout.LayoutParams.WRAP_CONTENT, android.widget.RelativeLayout.LayoutParams.WRAP_CONTENT);
GUI.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT));
GUI.setAnimationStyle(android.R.style.Animation_Translucent);
GUI.showAtLocation(ctx.getWindow().getDecorView(), android.view.Gravity.RIGHT | android.view.Gravity.TOP, 50, 0);
}}));

}

ctx.runOnUiThread(new java.lang.Runnable(){
run:function(){

android.widget.Toast.makeText(ctx,new android.text.Html.fromHtml("<b><font color=#FF0000>Mostly </b><b><font color=#FFFF00>Needed </b><b><font color=#00FF00>Tool  </b><b><font color=#0000FF>Mod </b><b><font color=#FFFFFF>2.0</b>"),0).show();
android.widget.Toast.makeText(ctx,new android.text.Html.fromHtml("<b><font color=#00FF00>Mostly </b><b><font color=#FF0000>Needed </b><b><font color=#FFFF00>Tool  </b><b><font color=#0000FF>Mod </b><b><font color=#FFFFFF>2.0</b>"),0).show();
android.widget.Toast.makeText(ctx,new android.text.Html.fromHtml("<b><font color=#FFFF00>Mostly </b><b><font color=#00FF00>Needed </b><b><font color=#FF0000>Tool  </b><b><font color=#0000FF>Mod </b><b><font color=#FFFFFF>2.0</b>"),0).show();
android.widget.Toast.makeText(ctx,new android.text.Html.fromHtml("<b><font color=#FF00FF>This Mod Was Made By:</b>"),1).show();
android.widget.Toast.makeText(ctx,new android.text.Html.fromHtml("<b><font color=#FF0000>| MCPEMoverz |</b>"),0).show();
android.widget.Toast.makeText(ctx,new android.text.Html.fromHtml("<b><font color=#FFFF00>| MCPEMoverz |</b>"),0).show();
android.widget.Toast.makeText(ctx,new android.text.Html.fromHtml("<b><font color=#00FF00>| MCPEMoverz |</b>"),0).show();

}});

function Base64Decode(byteArray, Path){
var file = new java.io.File(Path);

if (!file.exists()){
file.createNewFile();

var Stream = new java.io.FileOutputStream(file);
Stream.write(byteArray);
Stream.close();
}

}

function exit(){

ctx.runOnUiThread(new java.lang.Runnable({run: function(){

var xLayout = new android.widget.LinearLayout(ctx);

var xButton = new android.widget.Button(ctx);
xButton.setText('X');
xButton.setTextSize(textSize);
xButton.setTextColor(Color);
xButton.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
exitUI.dismiss();
menu.dismiss();
firstButton();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}
}));
xLayout.addView(xButton);

exitUI = new android.widget.PopupWindow(xLayout, dip2px(40), dip2px(40));
exitUI.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT));
exitUI.setAnimationStyle(android.R.style.Animation_Translucent);
exitUI.showAtLocation(ctx.getWindow().getDecorView(), android.view.Gravity.RIGHT | android.view.Gravity.TOP, 0, 0);
}}));

}

var once = false;

function openMenu(){

ctx.runOnUiThread(new java.lang.Runnable({run: function(){

var menuLayout = new android.widget.LinearLayout(ctx);
var menuScroll = new android.widget.ScrollView(ctx);
var menuLayout1 = new android.widget.LinearLayout(ctx);
menuLayout.setOrientation(1);
menuLayout1.setOrientation(1);
menuScroll.addView(menuLayout);
menuLayout1.addView(menuScroll);

var title = new android.widget.TextView(ctx);
title.setText("Mostly Needed Tool Mod [MCPEMoverz] | Hello "+ Player.getName(Player.getEntity()) +"!");
title.setTextSize(22);
title.setTextColor(Color);
title.setSingleLine();
title.setSelected(true);
title.setEllipsize(android.text.TextUtils.TruncateAt.MARQUEE);
title.setMarqueeRepeatLimit(-1);
menuLayout.addView(title);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var btn1 = new android.widget.Button(ctx);
btn1.setText('Pause/Play Game');
btn1.setTextSize(textSize);
btn1.setTextColor(Color);
btn1.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
if(!paused){
ModPE.setGameSpeed(0);
paused = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Game Is Now Pause!");
}else{
ModPE.setGameSpeed(20);
paused = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Game Is Now Play!");
}
}}));
menuLayout.addView(btn1);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var clearinv = new android.widget.Button(ctx);
clearinv.setText('Clear Inventory');
clearinv.setTextSize(textSize);
clearinv.setTextColor(Color);
clearinv.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
for(var i = 1; i <= 44; i++){
Player.clearInventorySlot(i);
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Your Inventory Has Been Cleared!");
}}));
menuLayout.addView(clearinv);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var pointedid = new android.widget.Button(ctx);
pointedid.setText('Get The Item You Pointing On');
pointedid.setTextSize(textSize);
pointedid.setTextColor(Color);
pointedid.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Player.addItemInventory(Player.getPointedBlockId(), 1, Player.getPointedBlockData());
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("An Item "+ Player.getPointedBlockId() +" With A Data of "+ Player.getPointedBlockData() +" Is Given To "+ Player.getName(getPlayerEnt()));
}}));
menuLayout.addView(pointedid);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var tmi = new android.widget.Button(ctx);
tmi.setText('Too Many Items');
tmi.setTextSize(textSize);
tmi.setTextColor(Color);
tmi.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
tooManyItems();
}
}));
menuLayout.addView(tmi);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var health = new android.widget.Button(ctx);
health.setText("Health");
health.setTextSize(textSize);
health.setTextColor(Color);
health.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
healthChange();
}}));
menuLayout.addView(health);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var changeGm = new android.widget.Button(ctx);
changeGm.setText('Change Gamemode');
changeGm.setTextSize(textSize);
changeGm.setTextColor(Color);
changeGm.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
changeGamemode();
}}));
menuLayout.addView(changeGm);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var tp = new android.widget.Button(ctx);
tp.setText('Teleport');
tp.setTextSize(textSize);
tp.setTextColor(Color);
tp.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
teleport();
}
}));
menuLayout.addView(tp);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var autoArmor = new android.widget.Button(ctx);
autoArmor.setText('Auto Armor');
autoArmor.setTextSize(textSize);
autoArmor.setTextColor(Color);
autoArmor.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
fastArmor();
}}));
menuLayout.addView(autoArmor);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var timeBtn = new android.widget.Button(ctx);
timeBtn.setText("Time");
timeBtn.setTextSize(textSize);
timeBtn.setTextColor(Color);
timeBtn.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
Time();
}
}));
menuLayout.addView(timeBtn);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var lvl = new android.widget.Button(ctx);
lvl.setText('Level');
lvl.setTextSize(textSize);
lvl.setTextColor(Color);
lvl.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
levelChange();
}});
menuLayout.addView(lvl);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var weather = new android.widget.Button(ctx);
weather.setText('Weather');
weather.setTextSize(textSize);
weather.setTextColor(Color);
weather.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
weatherChange();
}});
menuLayout.addView(weather);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var infoOn = new android.widget.Switch(ctx);
infoOn.setText('Show Debug');
infoOn.setTextSize(textSize);
infoOn.setTextColor(Color);
infoOn.setChecked(switched);
infoOn.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener({
onCheckedChanged: function(){
if(!switched){
switched = true;
showDebug();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Debug Information Has Been Showed!");
}else{
switched = false;
info.dismiss();
show = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Debug Information Has Been Hidden!");
}
}}));
menuLayout.addView(infoOn);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var fun = new android.widget.Switch(ctx);
fun.setText('Fun Mode');
fun.setTextSize(textSize);
fun.setTextColor(Color);
fun.setChecked(switched2);
fun.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener({
onCheckedChanged: function(){
if(!switched2){
switched2 = true;
funMode();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Fun Mode Has Been Showed!");
}else{
switched2 = false;
FunMode.dismiss();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Fun Mode Has Been Hidden!");
}
}}));
menuLayout.addView(fun);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var tag = new android.widget.Switch(ctx);
tag.setText('Show Mob`s Health');
tag.setTextSize(textSize);
tag.setTextColor(Color);
tag.setChecked(nameTagHealth);
tag.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener({
onCheckedChanged: function(){
if(!nameTagHealth){
nameTagHealth = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Mob's Health Has Been Enabled! Point To A Mob.");
new android.widget.Toast.makeText(ctx,new android.text.Html.fromHtml("<b><font color=#FF0000>REMINDER: </b><b><font color=#FFFF00>This Might Crash If Point To An Entity. (Like Primed TNT)</b>"),1).show();
}else{
nameTagHealth = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Mob's Health Has Been Disabled!");
}
}}));
menuLayout.addView(tag);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var fly = new android.widget.Switch(ctx);
fly.setText('Fly');
fly.setTextSize(textSize);
fly.setTextColor(Color);
fly.setChecked(switched3);
fly.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener({
onCheckedChanged: function(){
if(!switched3){
switched3 = true;
Player.setCanFly(true);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Flying Is Now Enabled!");
}else{
switched3 = false;
Player.setCanFly(false);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Flying Is Now Disabled!");
}
}}));
menuLayout.addView(fly);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var net = new android.widget.Button(ctx);
net.setText('Open Internet');
net.setTextSize(textSize);
net.setTextColor(Color);
net.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
linkPlace();
}}));
menuLayout.addView(net);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var settingBtn = new android.widget.Button(ctx);
settingBtn.setText("Settings");
settingBtn.setTextSize(textSize);
settingBtn.setTextColor(Color);
settingBtn.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
Settings();
}
}));
menuLayout.addView(settingBtn);

var title = new android.widget.TextView(ctx);
title.setText("\n");
menuLayout.addView(title);

var aboutBtn = new android.widget.Button(ctx);
aboutBtn.setText('About');
aboutBtn.setTextSize(textSize);
aboutBtn.setTextColor(Color);
aboutBtn.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
about();
}}));
menuLayout.addView(aboutBtn);

menu = new android.widget.PopupWindow(menuLayout1, ctx.getWindowManager().getDefaultDisplay().getWidth()/1.8, ctx.getWindowManager().getDefaultDisplay().getHeight()/1.8);
menu.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT));
menu.setAnimationStyle(android.R.style.Animation_Translucent);
menu.showAtLocation(ctx.getWindow().getDecorView(), android.view.Gravity.CENTER, 0, 0);
}}));

}

function fastArmor(){

ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(1);

var scroll = new android.widget.ScrollView(ctx);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("Auto Armor");

var btn1 = new android.widget.Button(ctx);
btn1.setText("A Set Of Diamond Armor");
btn1.setTextSize(textSize);
btn1.setTextColor(Color);
btn1.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Player.setArmorSlot(0, 310, 0);
Player.setArmorSlot(1, 311, 0);
Player.setArmorSlot(2, 312, 0);
Player.setArmorSlot(3, 313, 0);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Awesome Armor!");
}});
layout.addView(btn1);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var btn2 = new android.widget.Button(ctx);
btn2.setText("A Set Of Gold Armor");
btn2.setTextSize(textSize);
btn2.setTextColor(Color);
btn2.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Player.setArmorSlot(0, 314, 0);
Player.setArmorSlot(1, 315, 0);
Player.setArmorSlot(2, 316, 0);
Player.setArmorSlot(3, 317, 0);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Great Armor!");
}});
layout.addView(btn2);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var btn3 = new android.widget.Button(ctx);
btn3.setText("A Set Of Iron Armor");
btn3.setTextSize(textSize);
btn3.setTextColor(Color);
btn3.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Player.setArmorSlot(0, 306, 0);
Player.setArmorSlot(1, 307, 0);
Player.setArmorSlot(2, 308, 0);
Player.setArmorSlot(3, 309, 0);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Great Armor!");
}});
layout.addView(btn3);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var btn4 = new android.widget.Button(ctx);
btn4.setText("A Set Of Chainmail Armor");
btn4.setTextSize(textSize);
btn4.setTextColor(Color);
btn4.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Player.setArmorSlot(0, 302, 0);
Player.setArmorSlot(1, 303, 0);
Player.setArmorSlot(2, 304, 0);
Player.setArmorSlot(3, 305, 0);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Nice Armor!");
}});
layout.addView(btn4);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var btn5 = new android.widget.Button(ctx);
btn5.setText("A Set Of Leather Armor");
btn5.setTextSize(textSize);
btn5.setTextColor(Color);
btn5.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Player.setArmorSlot(0, 298, 0);
Player.setArmorSlot(1, 299, 0);
Player.setArmorSlot(2, 300, 0);
Player.setArmorSlot(3, 301, 0);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Better Armor.");
}});
layout.addView(btn5);

dialog.show();

}});

}

function teleport()
{
ctx.runOnUiThread(new java.lang.Runnable({run: function(){

var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(1);

var scroll = new android.widget.ScrollView(ctx);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("Teleport");

var txt = new android.widget.TextView(ctx);
txt.setText("Place Your Desired XYZ Coordinates Below\n");
txt.setTextSize(textSize);
txt.setTextColor(Color);
layout.addView(txt);

var eT1 = new android.widget.EditText(ctx); 
eT1.setHint('X | Your X: '+ Math.round(Player.getX()));
layout.addView(eT1);

var eT2 = new android.widget.EditText(ctx);
eT2.setHint('Y | Your Y: '+ Math.round(Player.getY()));
layout.addView(eT2);

var eT3 = new android.widget.EditText(ctx); 
eT3.setHint('Z | Your Z: '+ Math.round(Player.getZ()));
layout.addView(eT3);

var button = new android.widget.Button(ctx);
button.setText("Teleport");
button.setTextSize(textSize);
button.setTextColor(Color);
button.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
dialog.dismiss();
setPosition(getPlayerEnt(),eT1.getText(),eT2.getText(),eT3.getText());
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("You Set Your Position To X: "+ eT1.getText() +" | Y: "+ eT2.getText() +" | Z: "+ eT3.getText());
}
}));
layout.addView(button);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var spawnChange = new android.widget.Button(ctx);
spawnChange.setText('Set Spawn');
spawnChange.setTextSize(textSize);
spawnChange.setTextColor(Color);
spawnChange.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
Level.setSpawn(Player.getX(),Player.getY(),Player.getZ());
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("You Set Your Spawn Position To: "+ Math.floor(Player.getX()) +" / "+ Math.floor(Player.getY()) +" / "+ Math.floor(Player.getZ()));
}});
layout.addView(spawnChange);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var setHome = new android.widget.Button(ctx);
setHome.setText('Set Home');
setHome.setTextSize(textSize);
setHome.setTextColor(Color);
setHome.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

ModPE.saveData("homeX", Player.getX());
ModPE.saveData("homeY", Player.getY());
ModPE.saveData("homeZ", Player.getZ());
ModPE.saveData("homeSet", "canHome");
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Your Home Has Been Set To X: "+ Math.round(Player.getX()) +" Y: "+ Math.round(Player.getY()) +" Z: "+ Math.round(Player.getZ()));

if(!once){
new android.widget.Toast.makeText(ctx,"This Position Will Be Save Even You Exit Minecraft.",1).show();
once = true;
}
}}));
layout.addView(setHome);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var home = new android.widget.Button(ctx);
home.setText('Go To Home');
home.setTextSize(textSize);
home.setTextColor(Color);
home.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

if(ModPE.readData("homeSet") != "canHome") toast("You Haven't Set Your Home Position Yet!");

if(ModPE.readData("homeSet") == "canHome"){
setPosition(Player.getEntity(),ModPE.readData("homeX"),ModPE.readData("homeY"),ModPE.readData("homeZ"));
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("You Are Now On Your Home!");
}
}}));
layout.addView(home);

dialog.show();
}}));

}

function linkPlace()
{
var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(1);

var alert = new android.app.AlertDialog.Builder(ctx);
alert.setTitle('Internet');
alert.setView(layout);

var note = new android.widget.TextView(ctx); 
note.setText('↓ Type The Link Here ↓');
note.setTextColor(Color);
note.setTextSize(textSize);
layout.addView(note);

e1 = new android.widget.EditText(ctx); 
e1.setHint('example: www.facebook.com');
layout.addView(e1);

alert.setPositiveButton('Ok', new android.content.DialogInterface.OnClickListener(){ 
onClick: function(v){
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("You Are Directing To: "+ e1.getText().toString());
openInternet();
}});

alert.setNegativeButton('Cancel', new android.content.DialogInterface.OnClickListener(){
onClick: function(v){
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}});

alert.create().show();

}

function openInternet()
{
ctx.runOnUiThread(new java.lang.Runnable({
run: function(){

var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(1);

var webs = new android.webkit.WebView(ctx);
webs.getSettings().setJavaScriptEnabled(true);
webs.setWebChromeClient(new android.webkit.WebChromeClient());
webs.setWebViewClient(new android.webkit.WebViewClient());
webs.loadUrl(e1.getText().toString());
layout.addView(webs);

var change = new android.widget.Button(ctx);
change.setText('Change Link');
change.setTextSize(textSize);
change.setTextColor(Color);
change.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

netAccess.dismiss();
linkPlace();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(change);

var close = new android.widget.Button(ctx);
close.setText('Exit');
close.setTextSize(textSize);
close.setTextColor(Color);
close.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
netAccess.dismiss();
}}));
layout.addView(close);

netAccess = new android.widget.PopupWindow(layout, ctx.getWindowManager().getDefaultDisplay().getWidth(), ctx.getWindowManager().getDefaultDisplay().getHeight());
netAccess.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.BLACK));
netAccess.setAnimationStyle(android.R.style.Animation_Translucent);
netAccess.showAtLocation(ctx.getWindow().getDecorView(), android.view.Gravity.CENTER, 0, 0);

}}));


}

function levelChange()
{
ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(1);

var scroll = new android.widget.ScrollView(ctx);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("Level:");

var guide1 = new android.widget.TextView(ctx);
guide1.setText("↓ Change Your Level/Exp. Here ↓\n");
guide1.setTextSize(textSize);
guide1.setTextColor(Color);
layout.addView(guide1);

var lvl = new android.widget.EditText(ctx);
lvl.setHint('Put Your Desired Level Here (value)');
lvl.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(lvl);

var set1 = new android.widget.Button(ctx);
set1.setText('Set Value');
set1.setTextSize(textSize);
set1.setTextColor(Color);
set1.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
dialog.dismiss();
Player.setLevel(lvl.getText());
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Your Level Has Been Set To "+ lvl.getText().toString());
}}));
layout.addView(set1);

dialog.show();
}});

}

function about(){

ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

var layout = new android.widget.LinearLayout(ctx);

var scroll = new android.widget.ScrollView(ctx);
layout.setOrientation(1);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("About");

var intro = "Mostly Needed Tool (MNT) Mod 2.0\n\nThis Mod Was Made By: MCPEMoverz\n\nYou Can Use This Mod To Enjoy Yourself Or Help You On Your Survival. And Many More.\n";

var changelog2 = "\nChangelogs:\n\n2.0:\n\n- Achieved 2100+ Lines Of Code! (Finally, And Possible To Increase!)\n- Color White Debug Text\n- Added Item And Block ID List (Now, I Am Comfortably To Say That It's Too Many Items)\n- Added Auto Armor\n- Added Exploding Arrow (On Fun Mode)\n- Added Unlimited Items (On Fun Mode)\n- Click Button Sound (The Sound Is The Same As Game Button Sound)\n- Die Score (If Die In The Game, It Tell You Your Score)\n- Layout Animation\n- Added Changing Spawn Position (On Teleport)\n- Added Dimension Name (On Debug)\n- Added Game Score (On Debug)\n- Wall Climbing (On Fun Mode)\n- Level Customizing\n- Teleport Added (XYZ Coordinates)\n- Added In-Game Browser\n- Added World Name And World Folder Name (On Debug)\n- Added Game Pauseable And Playable\n- Added Walk Through Walls (On Fun Mode)\n- Added Click Thunder (On Fun Mode)\n- Clear Inventory Has Been Fixed\n- Gamemode Has Changed From One Click To Category\n- Funmode Has Been Grouped And Scrollable\n- GodMode Is Now Fixed (Placed On Fun Mode Category)\n- Set Home And Go To Home Is Now Added (On Teleport)\n- Rearrange Mod Menu\n- Settings Configuration Is Now Saveable (Even You Exit Minecraft, Your Settings Will Save.)\n- Showable Entity's Health And Color Indicator. (Just Point To An Entity. Make Sure That The Switch On The Menu Is On)\n- And Some Minor Bug Fixes\n";

var changelog1 = "\n1.0:\n\n- Initial Release\n- Too Many Items Added (Not Too Many Items Original)\n- If You Point A Block, You Can Get It On One Click.(Shown At The Menu)\n- You Can Change The Time Instantly And You Can Customize The Time On Your Own.\n- You Can Change The Weather.(rain, thunder, storm, and weather clear)\n- Fun Mode Added. You Can Accelerate and Bounce On Fun Mode. (Tell Me Your Suggestions About What I Will Add On Fun Mode. I'm lack of Idea. LOL)\n- Flying Added (If You Can't Fly, The Switch Will Turn Off. And If You Can Fly, The Button Will On)\n- You Can Change Your Gamemode Instantly On One Click.(Not Separated Button)\n- Added Settings So That You Can Do What Your Choice.\n- Transparent Menu. If You Activate The Menu, You Can Still Navigate Your Gameplay.\n- Debug Feature Added. You Have Now Information/Status On Your Character And Your World Status (Like The Same On PC)\n";

var updates = "\nWant To Be Always Updated?\n\nFollow Me On Twitter: @MCPEMoverz\nwww.twitter.com/mcpemoverz\n\nLike Me On Facebook: MCPEMoverz\nwww.facebook.com/mcpemoverz\n";

var bugs = "\nIf There Is Unexpected Bug, Crash Or Other Problems On This Mod, Message To Me That Problem On Twitter.\n\nIf You Have Suggestions About Features That I Will Add On This Mod (If Possible), Message Me On My Twitter.\n";

var outro = "\nThanks For Downloading! There's More On MNT v.3.0!! (Lots Of Possibilities, I Can Release That In A Short Period Of Time Because It's Vacation HEHEY!!) So Stay Tuned.\n";

var possibleOnV3 = "\n↓ This Are Possible On v.3.0 ↓\n\n- More Debugs?? Of Course. I Think I'll Gonna Make A Page 2 Of It\n- Menu Background?? I Think I'll Never To Put That. Why? Because If The Menu Background Is Not Transparent, You've Only Limited View On Your Screen.\n- Do You Want Me To Fullscreen The Menu?? So That You Can Customize The Background On It?? Put Your Suggestions On The Twitter (Below The Description).\n- More Fun Modes?? Yes! But Lack Of Idea. Tell Me Your Suggetions.\nPlaying Music From Sdcard? Sure! Just Make Sure That You Know The Directory.\n- Customizable Clicking Sound? Ok\n\nAnd A Lot More!!\n";

var directFollow = "\nYou Can Also Like and Follow Me Directly On Your Phone By Pressing This Buttons Below. Don't Worry, Your Game Will Never Close.\n\n";

var txt = new android.widget.TextView(ctx);
txt.setText(intro + changelog2 + changelog1 + updates + bugs + outro + possibleOnV3 + directFollow);
txt.setTextSize(textSize);
txt.setTextColor(Color);
layout.addView(txt);

var btn1 = new android.widget.Button(ctx);
btn1.setText('Go To My Twitter Directly "@MCPEMoverz"');
btn1.setTextSize(textSize);
btn1.setTextColor(Color);
btn1.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

var webs = new android.webkit.WebView(ctx);
webs.getSettings().setJavaScriptEnabled(true);
webs.setWebChromeClient(new android.webkit.WebChromeClient());
webs.setWebViewClient(new android.webkit.WebViewClient());
webs.loadUrl('www.twitter.com/mcpemoverz');
new android.app.AlertDialog.Builder(ctx).setView(webs).show();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(btn1);

var btn2 = new android.widget.Button(ctx);
btn2.setText('Go To My Facebook Directly "MCPEMoverz"');
btn2.setTextSize(textSize);
btn2.setTextColor(Color);
btn2.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

var webs = new android.webkit.WebView(ctx);
webs.getSettings().setJavaScriptEnabled(true);
webs.setWebChromeClient(new android.webkit.WebChromeClient());
webs.setWebViewClient(new android.webkit.WebViewClient());
webs.loadUrl('www.facebook.com/mcpemoverz');
new android.app.AlertDialog.Builder(ctx).setView(webs).show();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(btn2);

dialog.show();
}});

}

function changeGamemode(){

ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

var layout = new android.widget.LinearLayout(ctx);

var scroll = new android.widget.ScrollView(ctx);
layout.setOrientation(1);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("Change Gamemode To:");

var btn1 = new android.widget.Button(ctx);
btn1.setText('Survival');
btn1.setTextSize(textSize);
btn1.setTextColor(Color);
btn1.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Level.setGameMode(0);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("You Are Now Survival!");
}});
layout.addView(btn1);

var btn2 = new android.widget.Button(ctx);
btn2.setText('Creative');
btn2.setTextSize(textSize);
btn2.setTextColor(Color);
btn2.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Level.setGameMode(1);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("You Are Now Creative!");
}});
layout.addView(btn2);

dialog.show();
}});

}

function weatherChange(){

ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

var layout = new android.widget.LinearLayout(ctx);

var scroll = new android.widget.ScrollView(ctx);
layout.setOrientation(android.widget.LinearLayout.VERTICAL);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("Weather");

var clear = new android.widget.Button(ctx);
clear.setText('Weather Clear');
clear.setTextSize(textSize);
clear.setTextColor(Color);
clear.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Level.setLightningLevel(0);
Level.setRainLevel(0);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("The Weather Is Now Cleared!");
}});
layout.addView(clear);

var txt1 = new android.widget.TextView(ctx);
txt1.setText("\n↓ Rain ↓\n");
txt1.setTextSize(textSize);
txt1.setTextColor(Color);
layout.addView(txt1);

var rain = new android.widget.Button(ctx);
rain.setText('Raining (Weak)');
rain.setTextSize(textSize);
rain.setTextColor(Color);
rain.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Level.setRainLevel(0.5);
if(guide4 == false){
guide4 = true;
toast("Snow On Snow Biomes!");
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("It's Now Raining Weak!");
}});
layout.addView(rain);

var rain2 = new android.widget.Button(ctx);
rain2.setText('Raining (Strong)');
rain2.setTextSize(textSize);
rain2.setTextColor(Color);
rain2.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Level.setRainLevel(1);
if(guide4 == false){
guide4 = true;
toast("Snow On Snow Biomes!");
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("It's Now Raining Strong!");
}});
layout.addView(rain2);

var txt2 = new android.widget.TextView(ctx);
txt2.setText("\n↓ Thunder ↓\n");
txt2.setTextSize(textSize);
txt2.setTextColor(Color);
layout.addView(txt2);

var light = new android.widget.Button(ctx);
light.setText('Lightning (Weak)');
light.setTextSize(textSize);
light.setTextColor(Color);
light.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Level.setLightningLevel(0.5);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("It's Now Thundering Weak!");
}});
layout.addView(light);

var light2 = new android.widget.Button(ctx);
light2.setText('Lightning (Strong)');
light2.setTextSize(textSize);
light2.setTextColor(Color);
light2.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Level.setLightningLevel(1);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("It's Now Thundering Strong!");
}});
layout.addView(light2);

var txt3 = new android.widget.TextView(ctx);
txt3.setText("\n↓ Storm ↓\n");
txt3.setTextSize(textSize);
txt3.setTextColor(Color);
layout.addView(txt3);

var storm = new android.widget.Button(ctx);
storm.setText('Storming (Weak)');
storm.setTextSize(textSize);
storm.setTextColor(Color);
storm.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Level.setLightningLevel(0.5);
Level.setRainLevel(0.5);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("It's Now Storming Weak!");
}});
layout.addView(storm);

var storm2 = new android.widget.Button(ctx);
storm2.setText('Storming (Strong)');
storm2.setTextSize(textSize);
storm2.setTextColor(Color);
storm2.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Level.setLightningLevel(1);
Level.setRainLevel(1);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("It's Now Storming Strong!");
}});
layout.addView(storm2);

dialog.show();
}});

}

function healthChange(){

ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

var layout = new android.widget.LinearLayout(ctx);

var scroll = new android.widget.ScrollView(ctx);
layout.setOrientation(android.widget.LinearLayout.VERTICAL);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("Health");

var txt = new android.widget.TextView(ctx);
txt.setText("Current Health: "+ Entity.getHealth(getPlayerEnt()) +"\n");
txt.setTextSize(textSize);
txt.setTextColor(Color);
layout.addView(txt);

var heal = new android.widget.Button(ctx);
heal.setText('Heal');
heal.setTextSize(textSize);
heal.setTextColor(Color);
heal.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Player.setHealth(20);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("You've Been Healed!");
}});
layout.addView(heal);

var kill = new android.widget.Button(ctx);
kill.setText('Suicide');
kill.setTextSize(textSize);
kill.setTextColor(Color);
kill.setOnClickListener(new android.view.View.OnClickListener(){
onClick: function(v){
dialog.dismiss();
Player.setHealth(0);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("You've Commited Suicide!");
}});
layout.addView(kill);

dialog.show();
}});

}

var wallClimb = false;
var unliItems = false;

function funMode(){

ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(1);

var scroll = new android.widget.ScrollView(ctx);
      
var layout1 = new android.widget.LinearLayout(ctx);
      
layout.setOrientation(1);
layout1.setOrientation(1);
scroll.addView(layout);
layout1.addView(scroll);

var btn2 = new android.widget.Button(ctx);
btn2.setText('Accelerate');
btn2.setTextSize(textSize);
btn2.setTextColor(Color);
btn2.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
if(compass == "South (Towards Positive Z)"){
setVelZ(getPlayerEnt(), accelSpeed);
}else if(compass == "SouthWest (Between +Z and -X)"){
setVelZ(getPlayerEnt(), accelSpeed);
setVelX(getPlayerEnt(), -accelSpeed);
}else if(compass == "West (Towards Negative X)"){
setVelX(getPlayerEnt(), -accelSpeed);
}else if(compass == "NorthWest (Between -Z and -X)"){
setVelZ(getPlayerEnt(), -accelSpeed);
setVelX(getPlayerEnt(), -accelSpeed);
}else if(compass == "North (Towards Negative Z)"){
setVelZ(getPlayerEnt(), -accelSpeed);
}else if(compass == "NorthEast (Between -Z and +X)"){
setVelZ(getPlayerEnt(), -accelSpeed);
setVelX(getPlayerEnt(), accelSpeed);
}else if(compass == "East (Towards Positive X)"){
setVelX(getPlayerEnt(), accelSpeed);
}else if(compass == "SouthEast (Between +Z and +X)"){
setVelZ(getPlayerEnt(), accelSpeed);
setVelX(getPlayerEnt(), accelSpeed);
}else{
toast("Error Interface!");
}
}}));
layout.addView(btn2);

var btn1 = new android.widget.Button(ctx);
btn1.setText('Bounce');
btn1.setTextSize(textSize);
btn1.setTextColor(Color);
btn1.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

setVelY(getPlayerEnt(), bounceSpeed);
}}));
layout.addView(btn1);

var btn3 = new android.widget.Switch(ctx);
btn3.setText('Teleport On Tap');
btn3.setTextSize(textSize);
btn3.setTextColor(Color);
btn3.setChecked(telOn);
btn3.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){

if(!telOn){
telOn = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Teleport On Tap Is Now On! Tap On A Block.");
}else{
telOn = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Teleport On Tap Is Now Off!");
}
}});
layout.addView(btn3);

var btn4 = new android.widget.Switch(ctx);
btn4.setText('Explosive Punch');
btn4.setTextSize(textSize);
btn4.setTextColor(Color);
btn4.setChecked(punchOn);
btn4.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){

if(!punchOn){
punchOn = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Explosive Punch Is Now On! Tap On A Block.");
}else{
punchOn = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Explosive Punch Is Now Off!");
}
}});
layout.addView(btn4);

var god = new android.widget.Switch(ctx);
god.setText('God Mode');
god.setTextSize(textSize);
god.setTextColor(Color);
god.setChecked(godMode);
god.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){
if(!godMode){
godMode = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("God Mode/Infinite Health Is Now On!");
}else{
godMode = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("God Mode/Infinite Health Is Now Off!");
}
}});
layout.addView(god);

var noClip = new android.widget.Switch(ctx);
noClip.setText('Walk Through Walls');
noClip.setTextSize(textSize);
noClip.setTextColor(Color);
noClip.setChecked(switched5);
noClip.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){
if(!switched5){
switched5 = true;
Entity.setCollisionSize(Player.getEntity(), 0, 0);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Walk Through Walls Is Now Enabled!");
}else{
switched5 = false;
Entity.setCollisionSize(Player.getEntity(), 0.6, 1.8);
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Walk Through Walls Is Now Disabled!");
}
}});
layout.addView(noClip);

var btn5 = new android.widget.Switch(ctx);
btn5.setText('Click Thunder');
btn5.setTextSize(textSize);
btn5.setTextColor(Color);
btn5.setChecked(clickThunder);
btn5.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){

if(!clickThunder){
clickThunder = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Click Thunder Is Now On, Tap On A Block.");
}else{
clickThunder = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Click Thunder Is Now Off.");
}

}});
layout.addView(btn5);

var btn7 = new android.widget.Switch(ctx);
btn7.setText('Wall Climbing');
btn7.setTextSize(textSize);
btn7.setTextColor(Color);
btn7.setChecked(clickThunder);
btn7.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){

if(!wallClimb){
wallClimb = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Wall Climbing Is Now On.");
}else{
wallClimb = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Wall Climbing Is Now Off.");
}

}});
layout.addView(btn7);

var btn8 = new android.widget.Switch(ctx);
btn8.setText('Unlimited Items');
btn8.setTextSize(textSize);
btn8.setTextColor(Color);
btn8.setChecked(unliItems);
btn8.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){

if(!unliItems){
unliItems = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Unlimited Items Is Now On! Try To Place A Block. (Better On Survival)");
}else{
unliItems = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Unlimited Items Is Now Off!");
}
}});
layout.addView(btn8);

var btn9 = new android.widget.Switch(ctx);
btn9.setText('Exploding Arrow');
btn9.setTextSize(textSize);
btn9.setTextColor(Color);
btn9.setChecked(explodeArrow);
btn9.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){

if(!explodeArrow){
explodeArrow = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Exploding Arrow Is Now On!");
}else{
explodeArrow = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Exploding Arrow Is Now Off!");
}
}});
layout.addView(btn9);

var btn6 = new android.widget.Button(ctx);
btn6.setText('Falling Diamods');
btn6.setTextSize(textSize);
btn6.setTextColor(Color);
btn6.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

for(var i = 1; i <= 10; i++){

Level.dropItem(Player.getX(),100,Player.getZ(),0,264,5,0);
Level.dropItem(Player.getX()+i,100,Player.getZ(),0,264,5,0);
Level.dropItem(Player.getX()-i,100,Player.getZ(),0,264,5,0);
Level.dropItem(Player.getX(),100,Player.getZ()+i,0,264,5,0);
Level.dropItem(Player.getX(),100,Player.getZ()-i,0,264,5,0);
Level.dropItem(Player.getX()+i,100,Player.getZ()+i,0,264,5,0);
Level.dropItem(Player.getX()-i,100,Player.getZ()-i,0,264,5,0);
Level.dropItem(Player.getX()+i,100,Player.getZ()-i,0,264,5,0);
Level.dropItem(Player.getX()-i,100,Player.getZ()+i,0,264,5,0);
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("My Gift For You!");

}}));
layout.addView(btn6);

FunMode = new android.widget.PopupWindow(layout1, ctx.getWindowManager().getDefaultDisplay().getWidth()/2, ctx.getWindowManager().getDefaultDisplay().getHeight()/2);
FunMode.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT));
FunMode.setAnimationStyle(android.R.style.Animation_Translucent);
FunMode.showAtLocation(ctx.getWindow().getDecorView(), android.view.Gravity.TOP | android.view.Gravity.LEFT, 0, 0);
}});

}

function useItem(x, y, z, itemid, blockid, side, itemDamage, blockDamage){

if(clickThunder){
Level.spawnMob(x,y,z,EntityType.LIGHTNING_BOLT)
}
if(telOn){
setPosition(getPlayerEnt(),Player.getPointedBlockX(),Player.getPointedBlockY()+3,Player.getPointedBlockZ());
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}
if(punchOn){
explode(Player.getPointedBlockX(),Player.getPointedBlockY(),Player.getPointedBlockZ(),punchRadius,true);
}
if(unliItems){
addItemInventory(itemid,1, itemDamage);
}

}

var dimension = "";
var repeat = false;
var nameTagHealth = false;
var arrow;
var explodeArrow = false;
var alreadyExplode;
var explodeRadius = 3;

function modTick(){

var x = Player.getX();
var y = Player.getY();
var z = Player.getZ();

var fx = Math.floor(Player.getX());
var fy = Math.floor(Player.getY());
var fz = Math.floor(Player.getZ());

var rx = Math.round(Player.getX());
var ry = Math.round(Player.getY());
var rz = Math.round(Player.getZ());

var px = Player.getPointedBlockX();
var py = Player.getPointedBlockY();
var pz = Player.getPointedBlockZ();

if(Entity.getYaw(getPlayerEnt()) >= 360){
Entity.setRot(getPlayerEnt(), Entity.getYaw(getPlayerEnt()) - 360, Entity.getPitch(getPlayerEnt()));
}else if(Entity.getYaw(getPlayerEnt()) < 0){
Entity.setRot(getPlayerEnt(), Entity.getYaw(getPlayerEnt()) + 360, Entity.getPitch(getPlayerEnt()));
}
if(Entity.getYaw(getPlayerEnt()) > 0 && Entity.getYaw(getPlayerEnt()) < 22.5){
compass = "South (Towards Positive Z)";
}
if(Entity.getYaw(getPlayerEnt()) > 337.5 && Entity.getYaw(getPlayerEnt()) < 360){
compass = "South (Towards Positive Z)";
}
if(Entity.getYaw(getPlayerEnt()) > 22.5 && Entity.getYaw(getPlayerEnt()) < 67.5){
compass = "SouthWest (Between +Z and -X)";
}
if(Entity.getYaw(getPlayerEnt()) > 67.5 && Entity.getYaw(getPlayerEnt()) < 112.5){
compass = "West (Towards Negative X)";
}
if(Entity.getYaw(getPlayerEnt()) > 112.5 && Entity.getYaw(getPlayerEnt()) < 157.5){
compass = "NorthWest (Between -Z and -X)";
}
if(Entity.getYaw(getPlayerEnt()) > 157.5 && Entity.getYaw(getPlayerEnt()) < 202.5){
compass = "North (Towards Negative Z)";
}
if(Entity.getYaw(getPlayerEnt()) > 202.5 && Entity.getYaw(getPlayerEnt()) < 247.5){
compass = "NorthEast (Between -Z and +X)";
}
if(Entity.getYaw(getPlayerEnt()) > 247.5 && Entity.getYaw(getPlayerEnt()) < 292.5){
compass = "East (Towards Positive X)";
}
if(Entity.getYaw(getPlayerEnt()) > 292.5 && Entity.getYaw(getPlayerEnt()) < 337.5){
compass = "SouthEast (Between +Z and +X)";
}
if(nameTagHealth){
var nameColor = ChatColor.GREEN;
var pE = Player.getPointedEntity();
var eH = Entity.getHealth(pE);
var eMH = Entity.getMaxHealth(pE);

if(eH <= eMH/2) nameColor = ChatColor.YELLOW;
if(eH <= eMH/3.5) nameColor = ChatColor.RED;
Entity.setNameTag(pE,nameColor +"Health: "+ eH +" / "+ eMH);
}
if(Player.canFly() == false){
switched3 = false;
}else if(Player.canFly() == true){
switched3 = true;
}
if(alwaysDay) Level.setTime(1000);
if(alwaysNight) Level.setTime(14000);
if(godMode) Player.setHealth(30000);
if(wallClimb){
if(Level.getTile(x+1,y,z) != 0 || Level.getTile(x-1,y,z) != 0 || Level.getTile(x,y,z+1) != 0 || Level.getTile(x,y,z-1) != 0) setVelY(Player.getEntity(), 0.6);
}
if(Player.getDimension() == 0) dimension = "OverWorld";
if(Player.getDimension() == 1) dimension = "NetherWorld";
if(Entity.getHealth(Player.getEntity()) >= 1){
repeat = false;
}
if(Entity.getHealth(Player.getEntity()) <= 0 && repeat == false){
repeat = true;
ctx.runOnUiThread(new java.lang.Runnable(){run: function(){
new android.widget.Toast.makeText(ctx,"Score: "+ Player.getScore(),1).show();
}});
}
if(explodeArrow){
	if(Entity.getVelX(arrow) == 0 && Entity.getVelY(arrow) == 0 && Entity.getVelZ(arrow) == 0 && !alreadyExplode){
	explode(Entity.getX(arrow),Entity.getY(arrow),Entity.getZ(arrow),explodeRadius,true);
	alreadyExplode = true;
	}
}
if(show){
ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

infoText.setText("Mostly Needed Tool Mod 2.0 [MCPEMoverz]\nMinecraft Pocket Edition Version "+ ModPE.getMinecraftVersion() +"\nCoords (With Decimal): "+ getPlayerX() +" / "+ getPlayerY() +" / "+ getPlayerZ() +"\nCoords: "+ rx +" / "+ ry +" / "+ rz +"\nFacing: "+ compass +" ("+ Math.round(Entity.getYaw(getPlayerEnt())) +"° / "+ Math.round(Entity.getPitch(getPlayerEnt())) +"°)\nBiome: "+ Level.getBiomeName() +"\nLight Level: "+ Level.getBrightness(getPlayerX(), getPlayerY()-1, getPlayerZ()) +" ("+ Level.getBrightness(getPlayerX(), 128, getPlayerZ()) +" sky, 0 block)\nPointing On (X/Y/Z): "+ px +" / "+ py +" / "+ pz +"\nPointing On (ID/Data): "+ Player.getPointedBlockId() +" / "+ Player.getPointedBlockData() +"\nCarrying A (Item ID/Data): "+ Player.getCarriedItem() +" / "+ Player.getCarriedItemData() +"\nTime: "+ Level.getTime() +"\nName Of The World: "+ Level.getWorldName(getPlayerEnt()) +"\nWorld Folder Name: "+ Level.getWorldDir() +"\nDimension: "+ dimension +"\nScore: "+ Player.getScore() +"");

}});
}

}

function entityAddedHook(entity){

if(Entity.getEntityTypeId(entity) == EntityType.ARROW){
arrow = entity;
alreadyExplode = false;
}

}

var alwaysDay = false;
var alwaysNight = false;

function Time(){

ctx.runOnUiThread(new java.lang.Runnable({run: function(){
try{

var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(android.widget.LinearLayout.VERTICAL);

var scroll = new android.widget.ScrollView(ctx);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("Time Set To:");

var day = new android.widget.Button(ctx);
day.setText("Day");
day.setTextSize(textSize);
day.setTextColor(Color);
day.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
Level.setTime(1000);
dialog.dismiss();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("It's Now Day!");
}
}));
layout.addView(day);

var night = new android.widget.Button(ctx);
night.setText("Night");
night.setTextSize(textSize);
night.setTextColor(Color);
night.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
Level.setTime(14000);
dialog.dismiss();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("It's Now Night!");
}
}));
layout.addView(night);

var btn1 = new android.widget.Switch(ctx);
btn1.setText('Always Day');
btn1.setTextSize(textSize);
btn1.setTextColor(Color);
btn1.setChecked(alwaysDay);
btn1.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){
dialog.dismiss();
if(alwaysNight) alwaysNight = false;
if(!alwaysDay){
alwaysDay = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Always Day Is Now Enabled!");
}else{
alwaysDay = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Always Day Is Now Disabled!");
}
}});
layout.addView(btn1);

var btn2 = new android.widget.Switch(ctx);
btn2.setText('Always Night');
btn2.setTextSize(textSize);
btn2.setTextColor(Color);
btn2.setChecked(alwaysNight);
btn2.setOnCheckedChangeListener(new android.widget.CompoundButton.OnCheckedChangeListener(){
onCheckedChanged: function(){
dialog.dismiss();
if(alwaysDay) alwaysDay = false;
if(!alwaysNight){
alwaysNight = true;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Always Night Is Now Enabled!");
}else{
alwaysNight = false;
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("Always Night Is Now Disabled!");
}
}});
layout.addView(btn2);

var custom = new android.widget.TextView(ctx);
custom.setTextSize(textSize);
custom.setText("\n↓ Custom ↓\n");
layout.addView(custom);

var fillTime = new android.widget.EditText(ctx);
fillTime.setHint('Put Your Desired Time Here');
fillTime.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(fillTime);

var setTime = new android.widget.Button(ctx);
setTime.setText("Set");
setTime.setTextSize(textSize);
setTime.setTextColor(Color);
setTime.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){

Level.setTime(fillTime.getText());
dialog.dismiss();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("You Set The Custom Time To: "+ fillTime.getText().toString() +"!");
}
}));
layout.addView(setTime);

dialog.show();
}catch(err){print(err)}
}}));

}

function showDebug(){

ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(1);
      
infoText = new android.widget.TextView(ctx);
infoText.setTextSize(debugTextSize);
infoText.setText("Mostly Needed Tool Mod [MCPEMoverz]");
infoText.setTextColor(android.graphics.Color.WHITE);
infoText.setTypeface(modFont);
layout.addView(infoText);

info = new android.widget.PopupWindow(layout, android.widget.RelativeLayout.LayoutParams.WRAP_CONTENT, android.widget.RelativeLayout.LayoutParams.WRAP_CONTENT);
info.setTouchable(false);
info.setBackgroundDrawable(null);
info.setAnimationStyle(android.R.style.Animation_Translucent);
info.showAtLocation(ctx.getWindow().getDecorView(), android.view.Gravity.LEFT | android.view.Gravity.TOP, 0, 0);
show = true;
}});

}

function tooManyItems(){

ctx.runOnUiThread(new java.lang.Runnable({run: function(){

var layout = new android.widget.LinearLayout(ctx);
layout.setOrientation(1);

var scroll = new android.widget.ScrollView(ctx);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("↓ Too Many Items ↓");

var title = new android.widget.TextView(ctx);
title.setText("↓ Place The ItemId, ItemCount, And Item Data Here ↓");
title.setTextSize(textSize);
title.setTextColor(Color);
title.setEllipsize(android.text.TextUtils.TruncateAt.MARQUEE);
title.setMarqueeRepeatLimit(-1);
title.setSingleLine();
title.setSelected(true);
layout.addView(title);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var itemId = new android.widget.EditText(ctx); 
itemId.setHint('Item ID');
itemId.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(itemId);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var itemCount = new android.widget.EditText(ctx);
itemCount.setHint('Item Count/Amount');
itemCount.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(itemCount);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var itemData = new android.widget.EditText(ctx);
itemData.setHint('Item Damage/Data');
itemData.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(itemData);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var fullGive = new android.widget.Button(ctx);
fullGive.setText('Full Stack');
fullGive.setTextSize(textSize);
fullGive.setTextColor(Color);
fullGive.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
itemCount.setText("64");
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}
}));
layout.addView(fullGive);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var btn1 = new android.widget.Button(ctx);
btn1.setText('Give');
btn1.setTextSize(textSize);
btn1.setTextColor(Color);
btn1.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
dialog.dismiss();
Player.addItemInventory(itemId.getText().toString(),itemCount.getText().toString(),itemData.getText().toString());
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
toast("An ItemID "+ itemId.getText().toString() +" With A Count Of "+ itemCount.getText().toString() +" is Given To "+ Player.getName(getPlayerEnt()));
}
}));
layout.addView(btn1);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var title = new android.widget.TextView(ctx);
title.setText("↓ Here's The Item List And Block List ↓");
title.setTextSize(textSize);
title.setTextColor(Color);
layout.addView(title);

var title = new android.widget.TextView(ctx);
title.setText("\n");
layout.addView(title);

var itemList = 'BlockID → BlockName\n\n0 → "Air"\n1 → "Stone"\n2 → "Grass"\n3 → "Dirt"\n4 → "Cobblestone"\n5 → "WoodenPlank"\n6 → "Sapling"\n7 → "Bedrock"\n8 → "Water"\n9 → "StationaryWater"\n10 → "Lava"\n11 → "StationaryLava"\n12 → "Sand"\n13 → "Gravel"\n14 → "GoldOre"\n15 → "IronOre"\n16 → "CoalOre"\n17 → "Wood"\n18 → "Leaves"\n19 → "Sponge"\n20 → "Glass"\n21 → "LapisLazuliOre"\n22 → "LapisLazuliBlock"\n23 → "Dispenser"\n24 → "Sandstone"\n25 → "NoteBlock"\n26 → "Bed"\n27 → "PoweredRail"\n28 → "DetectorRail"\n29 → "StickyPiston"\n30 → "Cobweb"\n31 → "TallGrass"\n32 → "DeadShrub"\n35 → "Wool"\n37 → "YellowFlower"\n38 → "CyanFlower"\n39 → "BrownMushroom"\n40 → "RedMushroom"\n41 → "BlockofGold"\n42 → "BlockofIron"\n44 → "StoneSlab"\n45 → "Brick"\n46 → "TNT"\n47 → "Bookcase"\n48 → "MossStone"\n49 → "Obsidian"\n50 → "Torch"\n51 → "Fire"\n52 → "MobSpawner"\n53 → "WoodenStairs"\n56 → "DiamondOre"\n57 → "BlockofDiamond"\n58 → "Workbench"\n59 → "Wheat"\n60 → "Farmland"\n61 → "Furnace"\n62 → "Furnace"\n63 → "Sign"\n64 → "WoodDoor"\n65 → "Ladder"\n66 → "Rails"\n67 → "CobblestoneStairs"\n68 → "Sign"\n71 → "IronDoor"\n73 → "RedstoneOre"\n78 → "Snow"\n79 → "Ice"\n80 → "SnowBlock"\n81 → "Cactus"\n82 → "ClayBlock"\n83 → "SugarCane"\n85 → "Fence"\n87 → "Netherrack"\n88 → "SoulSand"\n89 → "Glowstone"\n96 → "Trapdoor"\n98 → "StoneBricks"\n99 → "BrownMushroom"\n100 → "RedMushroom"\n102 → "GlassPane"\n103 → "Melon"\n105 → "MelonVine"\n107 → "FenceGate"\n108 → "BrickStairs"\n109 → "StoneBrickStairs"\n112 → "NetherBrick"\n114 → "NetherBrickStairs"\n128 → "SandstoneStairs"\n155 → "BlockofQuartz"\n156 → "QuartzStairs"\n245 → "StoneCutter"\n246 → "GlowingObsidian"\n247 → "NetherReactorCore"\n\nItem List:\n\nItemID → ItemName\n\n256 → "IronShovel"\n257 → "IronPickaxe"\n258 → "IronAxe"\n259 → "FlintandSteel"\n260 → "Apple"\n261 → "Bow"\n262 → "Arrow"\n263 → "Coal"\n264 → "DiamondGem"\n265 → "IronIngot"\n266 → "GoldIngot"\n267 → "IronSword"\n268 → "WoodenSword"\n269 → "WoodenShovel"\n270 → "WoodenPickaxe"\n271 → "WoodenAxe"\n272 → "StoneSword"\n273 → "StoneShovel"\n274 → "StonePickaxe"\n275 → "StoneAxe"\n276 → "DiamondSword"\n277 → "DiamondShovel"\n278 → "DiamondPickaxe"\n279 → "DiamondAxe"\n280 → "Stick"\n281 → "Bowl"\n282 → "MushroomStew"\n283 → "GoldSword"\n284 → "GoldShovel"\n285 → "GoldPickaxe"\n286 → "GoldAxe"\n287 → "String"\n288 → "Feather"\n289 → "Gunpowder"\n290 → "WoodenHoe"\n291 → "StoneHoe"\n292 → "IronHoe"\n293 → "DiamondHoe"\n294 → "GoldHoe"\n295 → "WheatSeeds"\n296 → "Wheat"\n297 → "Bread"\n298 → "LeatherHelmet"\n299 → "LeatherChestplate"\n300 → "LeatherLeggings"\n301 → "LeatherBoots"\n302 → "ChainmailHelmet"\n303 → "ChainmailChestplate"\n304 → "ChainmailLeggings"\n305 → "ChainmailBoots"\n306 → "IronHelmet"\n307 → "IronChestplate"\n308 → "IronLeggings"\n309 → "IronBoots"\n310 → "DiamondHelmet"\n311 → "DiamondChestplate"\n312 → "DiamondLeggings"\n313 → "DiamondBoots"\n314 → "GoldHelmet"\n315 → "GoldChestplate"\n316 → "GoldLeggings"\n317 → "GoldBoots"\n318 → "Flint"\n319 → "RawPorkchop"\n320 → "CookedPorkchop"\n321 → "Painting"\n322 → "GoldApple"\n332 → "Snowball"\n334 → "Leather"\n336 → "ClayBrick"\n337 → "Clay"\n338 → "SugarCane"\n339 → "Paper"\n340 → "Book"\n344 → "Egg"\n348 → "GlowstoneDust"\n352 → "Bone"\n353 → "Sugar"\n355 → "Bed"\n359 → "Shears"\n360 → "Melon"\n362 → "MelonSeeds"\n363 → "RawBeef"\n364 → "Steak"\n365 → "RawChicken"\n366 → "CookedChicken"\n405 → "NetherBrick"\n456 → "Camera"';

var txt1 = new android.widget.TextView(ctx);
txt1.setText(itemList);
txt1.setTextSize(textSize);
txt1.setTextColor(Color);
layout.addView(txt1);

dialog.show();

}}));

}

function Settings(){

ctx.runOnUiThread(new java.lang.Runnable(){run: function(){

new android.widget.Toast.makeText(ctx,"If The Mod Told You To Repeat, It Means You Changed It Already Twice Or More And It Automatically Save.",1).show();
new android.widget.Toast.makeText(ctx,"Sometimes Settings Configuration Will Not Save. (If Happen, Just Repeat.)",1).show();

var layout = new android.widget.LinearLayout(ctx);

var scroll = new android.widget.ScrollView(ctx);
layout.setOrientation(android.widget.LinearLayout.VERTICAL);
scroll.addView(layout);

var dialog = new android.app.Dialog(ctx);
dialog.setContentView(scroll);
dialog.setTitle("Settings");

var guide1 = new android.widget.TextView(ctx);
guide1.setText("Menu Text Size (Only Menu)\nCurrent Is: "+ textSize +"\n");
guide1.setTextSize(textSize);
guide1.setTextColor(Color);
layout.addView(guide1);

var modText = new android.widget.EditText(ctx);
modText.setHint('Set Text Size (Default is 20)');
modText.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(modText);

var btn1 = new android.widget.Button(ctx);
btn1.setText('Set Size');
btn1.setTextSize(textSize);
btn1.setTextColor(Color);
btn1.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
if(ModPE.readData("MenuTextSize") >= 1){
ModPE.removeData("MenuTextSize");
toast("Reclick Set To Apply Changes.");
}else{
textSize = modText.getText();
ModPE.saveData("MenuTextSize", modText.getText());
exitUI.dismiss();
menu.dismiss();
dialog.dismiss();
firstButton();
toast("You Change The Text Size to "+ modText.getText().toString() +"!");
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(btn1);

var guide2 = new android.widget.TextView(ctx);
guide2.setText("\nDebug Text Size (Only Debug)\nCurrent Is: "+ debugTextSize +"\n");
guide2.setTextSize(textSize);
guide2.setTextColor(Color);
layout.addView(guide2);

var debugText = new android.widget.EditText(ctx);
debugText.setHint('Set Debug Text Size (Default is 12)');
debugText.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(debugText);

var btn2 = new android.widget.Button(ctx);
btn2.setText('Set Size');
btn2.setTextSize(textSize);
btn2.setTextColor(Color);
btn2.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
if(ModPE.readData("DebugSize") >= 1){
ModPE.removeData("DebugSize");
toast("Reclick Set To Apply Changes.");
}else{
dialog.dismiss();
debugTextSize = debugText.getText();
ModPE.saveData("DebugSize", debugText.getText());
toast("Restart Debug. (Switch Off Debug Then Switch It On Again.)");
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(btn2);

var guide3 = new android.widget.TextView(ctx);
guide3.setText("\nBounce Power (You Can Put A Decimal)\nCurrent Is: "+ bounceSpeed +"\n");
guide3.setTextSize(textSize);
guide3.setTextColor(Color);
layout.addView(guide3);

var bounce = new android.widget.EditText(ctx);
bounce.setHint('Set Bounce Power (Default is 1)');
bounce.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(bounce);

var btn3 = new android.widget.Button(ctx);
btn3.setText('Set');
btn3.setTextSize(textSize);
btn3.setTextColor(Color);
btn3.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
if(ModPE.readData("Bounce") >= 1){ ModPE.removeData("Bounce");
toast("Reclick Set To Apply Changes.");
}else{
dialog.dismiss();
bounceSpeed = bounce.getText();
ModPE.saveData("Bounce", bounce.getText());
toast("You Change The Bounce Power To "+ bounce.getText().toString() +"!");
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(btn3);

var guide4 = new android.widget.TextView(ctx);
guide4.setText("\nAccelerate Power (You Can Put A Decimal)\nCurrent Is: "+ accelSpeed +"\n");
guide4.setTextSize(textSize);
guide4.setTextColor(Color);
layout.addView(guide4);

var accel = new android.widget.EditText(ctx);
accel.setHint('Set Accelerate Power (Default is 2)');
accel.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(accel);

var btn4 = new android.widget.Button(ctx);
btn4.setText('Set');
btn4.setTextSize(textSize);
btn4.setTextColor(Color);
btn4.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
if(ModPE.readData("Accel") >= 1){ ModPE.removeData("Accel");
toast("Reclick Set To Apply Changes.");
}else{
dialog.dismiss();
accelSpeed = accel.getText();
ModPE.saveData("Accel", accel.getText());
toast("You Change The Accelerate Range To "+ accel.getText() +"!");
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(btn4);

var guide5 = new android.widget.TextView(ctx);
guide5.setText("\nExplosive Punch Radius\nCurrent Is: "+ punchRadius +"\n");
guide5.setTextSize(textSize);
guide5.setTextColor(Color);
layout.addView(guide5);

var punch = new android.widget.EditText(ctx);
punch.setHint('Set Explosive Punch Radius (Default is 3)');
punch.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(punch);

var btn5 = new android.widget.Button(ctx);
btn5.setText('Set');
btn5.setTextSize(textSize);
btn5.setTextColor(Color);
btn5.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
if(ModPE.readData("PunchRadius") >= 1){ ModPE.removeData("PunchRadius");
toast("Reclick Set To Apply Changes.");
}else{
dialog.dismiss();
punchRadius = punch.getText();
ModPE.saveData("PunchRadius", punch.getText());
toast("You Change The Explosive Punch Radius To "+ punch.getText().toString() +"!");
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(btn5);

var guide7 = new android.widget.TextView(ctx);
guide7.setText("\nExploding Arrow Radius\nCurrent Is: "+ explodeRadius +"\n");
guide7.setTextSize(textSize);
guide7.setTextColor(Color);
layout.addView(guide7);

var arrowEdit = new android.widget.EditText(ctx);
arrowEdit.setHint('Set Arrow Explosion Radius (Default is 3)');
arrowEdit.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
layout.addView(arrowEdit);

var btn6 = new android.widget.Button(ctx);
btn6.setText('Set');
btn6.setTextSize(textSize);
btn6.setTextColor(Color);
btn6.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
if(ModPE.readData("ExplodeArrowRadius") >= 1){
ModPE.removeData("ExplodeArrowRadius");
toast("Reclick Set To Apply Changes.");
}else{
dialog.dismiss();
explodeRadius = arrowEdit.getText();
ModPE.saveData("ExplodeArrowRadius", arrowEdit.getText());
toast("You Change The Explosive Arrow Radius To "+ arrowEdit.getText().toString() +"!");
}
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
}}));
layout.addView(btn6);

var guide6 = new android.widget.TextView(ctx);
guide6.setText("\nReset All To Default\n");
guide6.setTextSize(textSize);
guide6.setTextColor(Color);
layout.addView(guide6);

var defaultBtn = new android.widget.Button(ctx);
defaultBtn.setText('Reset All Settings To Default');
defaultBtn.setTextSize(textSize);
defaultBtn.setTextColor(Color);
defaultBtn.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(v){
ModPE.removeData("PunchRadius");
ModPE.removeData("Accel");
ModPE.removeData("Bounce");
ModPE.removeData("DebugSize");
ModPE.removeData("MenuTextSize");
ModPE.removeData("ExplodeArrowRadius");
punchRadius = 3;
accelSpeed = 2;
bounceSpeed = 1;
debugTextSize = 12;
textSize = 20;
explodeRadius = 3;
dialog.dismiss();
menu.dismiss();
exitUI.dismiss();
firstButton();
Level.playSound(Player.getX(), Player.getY(), Player.getZ(), clickSound, 100);
new android.widget.Toast.makeText(ctx,"All Settings Has Been Reset To Default, And Saved Settings Has Been Deleted.",1).show();
}}));
layout.addView(defaultBtn);

dialog.show();
}});

}

function toast(str){

ctx.runOnUiThread(new java.lang.Runnable(){ run: function(){

new android.widget.Toast.makeText(ctx,str,0).show();

}});

}

function leaveGame(){

ctx.runOnUiThread(new java.lang.Runnable({ run: function(){

if(GUI != null){
GUI.dismiss();
GUI = null;
}
if(menu != null){
menu.dismiss();
menu = null;
}
if(exitUI != null){
exitUI.dismiss();
exitUI = null;
}
if(info != null){
info.dismiss();
info = null;
}
if(FunMode != null){
FunMode.dismiss();
FunMode = null;
}
if(netAccess != null){
netAccess.dismiss();
netAccess = null;
}

}}));
switched = false;
switched2 = false;

}